export const customEventType = {
    beforeCopied: 'beforeCopied',
    updateHeader: 'updateHeader',
    afterWebsocket: 'afterWebsocket',
    afterCopied: 'afterCopied',
    beforeDeleted: 'beforeDeleted',
    afterDeleted: 'afterDeleted',
    deactivated: 'Deactivated',
    beforePasted: 'beforePasted',
    afterPasted: 'afterPasted',
    beforeCreated: 'beforeCreated',
    afterCreated: 'afterCreated',
    beforeEmptyRowCreated: 'beforeEmptyRowCreated',
    afterEmptyRowCreated: 'afterEmptyRowCreated',
    beforeCreatedList: 'beforeCreatedList',
    afterCreatedList: 'afterCreatedList',
    selected: 'Selected',
    rowFocusIn: 'rowFocusIn',
    rowFocusOut: 'rowFocusOut',
    rowMouseEnter: 'rowMouseEnter',
    rowMouseLeave: 'rowMouseLeave',
    openRef: 'openRef',
    beforePatchUpdate: 'beforePatchUpdate',
    validatePatchUpdate: 'validatePatchUpdate',
    beforePatchCreate: 'beforePatchCreate',
    afterPatchUpdate: 'afterPatchUpdate',
};

export const typeEntityAction = {
    updateEntity: 1,
    updateCountBadge: 2,
    message: 3,
    messageCountBadge: 4,
};