services:
  coreapi:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    command: >
      bash -c "cd CoreAPI &&
               dotnet restore &&
               dotnet watch run --urls=http://+:80"
  
  frontend:
    image: node:18-alpine
    volumes:
      - ./fe:/app
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "pnpm install &&
             pnpm run dev -- --host"
    depends_on:
      - coreapi