services:
  coreapi:
    build:
      context: ./CoreAPI
      dockerfile: Dockerfile
    volumes:
      - ./CoreAPI:/app
    ports:
      - "8080:80"
      - "2222:2222"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - coreapi