version: '3.8'

services:

  coreapi:
    build:
      context: ./CoreAPI
      dockerfile: Dockerfile
    volumes:
      - ./CoreAPI:/app
    ports:
      - "8080:80"
      - "2222:2222"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: node:20-alpine  # Use an appropriate Node.js image
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"  # Vite dev server with host flag
    depends_on:
      - coreapi
