using System;
using System.Collections.Generic;

namespace TMS.API.Models
{
    public partial class Transportation
    {
        public Transportation()
        {
            Expense = new HashSet<Expense>();
            Revenue = new HashSet<Revenue>();
        }

        public int Id { get; set; }
        public int? QuotationClosingId { get; set; }
        public int? QuotationReturnId { get; set; }
        public int? QuotationEmptyLiftId { get; set; }
        public int? QuotationLandingId { get; set; }
        public bool IsLocation { get; set; }
        public int? ExportListId { get; set; }
        public int? ExportListReturnId { get; set; }
        public int? RouteId { get; set; }
        public int? BookingId { get; set; }
        public int? TransportationPlanId { get; set; }
        public int? BrandShipId { get; set; }
        public int? LineId { get; set; }
        public int? ShipId { get; set; }
        public string Trip { get; set; }
        public string BillNo { get; set; }
        public DateTime? ClosingDate { get; set; }
        public DateTime? StartShip { get; set; }
        public int? ClosingId { get; set; }
        public int? SocId { get; set; }
        public string SplitBill { get; set; }
        public bool IsEmptyCombination { get; set; }
        public int? EmptyCombinationId { get; set; }
        public int? EmptyId { get; set; }
        public bool IsClosingCustomer { get; set; }
        public int? ContainerTypeId { get; set; }
        public string ContainerNo { get; set; }
        public string SealNo { get; set; }
        public int? BossId { get; set; }
        public int? UserId { get; set; }
        public int? CommodityId { get; set; }
        public decimal Cont20 { get; set; }
        public decimal Cont40 { get; set; }
        public decimal? Weight { get; set; }
        public int? ReceivedId { get; set; }
        public string ClosingNotes { get; set; }
        public string ClosingUserId { get; set; }
        public string ClosingDriverId { get; set; }
        public string ClosingTruckId { get; set; }
        public int? PickupEmptyId { get; set; }
        public int? PortLoadingId { get; set; }
        public bool IsClampingFee { get; set; }
        public bool IsClampingReturnFee { get; set; }
        public decimal? ClosingUnitPrice { get; set; }
        public decimal? ClosingPercent { get; set; }
        public decimal? ClosingCombinationUnitPrice { get; set; }
        public bool IsEmptyLift { get; set; }
        public bool IsLanding { get; set; }
        public decimal? LiftFee { get; set; }
        public decimal? LandingFee { get; set; }
        public decimal? ClosingFee { get; set; }
        public decimal? CheckFee { get; set; }
        public decimal? CombinationFee { get; set; }
        public decimal? OrtherFee { get; set; }
        public decimal? OrtherFeeInvoinceNo { get; set; }
        public decimal? CollectOnBehaftFee { get; set; }
        public decimal? CollectOnBehaftInvoinceNoFee { get; set; }
        public decimal? InsuranceFee { get; set; }
        public decimal? TotalFee { get; set; }
        public decimal? ShipUnitPrice { get; set; }
        public decimal? ShipPolicyPrice { get; set; }
        public int? PolicyId { get; set; }
        public decimal? ShipPrice { get; set; }
        public decimal? ShipRoses { get; set; }
        public string ShipNotes { get; set; }
        public bool LockShip { get; set; }
        public DateTime? ShipDate { get; set; }
        public decimal? Dem { get; set; }
        public DateTime? DemDate { get; set; }
        public DateTime? LeftDate { get; set; }
        public DateTime? ReturnDate { get; set; }
        public DateTime? ClosingCont { get; set; }
        public decimal? ShellDate { get; set; }
        public int? ReturnId { get; set; }
        public string ReturnNotes1 { get; set; }
        public string ReturnNotes { get; set; }
        public string ReturnUserId { get; set; }
        public int? ReturnVendorId { get; set; }
        public string ReturnDriverId { get; set; }
        public string ReturnTruckId { get; set; }
        public string NotificationCount { get; set; }
        public string Bet { get; set; }
        public int? PortLiftId { get; set; }
        public int? ReturnEmptyId { get; set; }
        public decimal? ReturnUnitPrice { get; set; }
        public bool IsLiftFee { get; set; }
        public bool IsClosingEmptyFee { get; set; }
        public decimal? ReturnLiftFee { get; set; }
        public decimal? ReturnClosingFee { get; set; }
        public decimal? ReturnDo { get; set; }
        public decimal? ReturnVs { get; set; }
        public decimal? ReturnCheckFee { get; set; }
        public decimal? ReturnOrtherFee { get; set; }
        public decimal? ReturnOrtherInvoinceFee { get; set; }
        public decimal? ReturnCollectOnBehaftFee { get; set; }
        public decimal? ReturnCollectOnBehaftInvoinceFee { get; set; }
        public decimal? ReturnPlusFee { get; set; }
        public decimal? ReturnTotalFee { get; set; }
        public bool IsKt { get; set; }
        public bool IsSubmit { get; set; }
        public string LotNo { get; set; }
        public DateTime? LotDate { get; set; }
        public string InvoinceNo { get; set; }
        public DateTime? InvoinceDate { get; set; }
        public decimal? Vat { get; set; }
        public decimal? UnitPriceBeforeTax { get; set; }
        public decimal? UnitPriceAfterTax { get; set; }
        public decimal? ReceivedPrice { get; set; }
        public decimal? CollectOnBehaftPrice { get; set; }
        public decimal? TotalPriceBeforTax { get; set; }
        public decimal? VatPrice { get; set; }
        public decimal? TotalPrice { get; set; }
        public decimal? TotalPriceAfterTax { get; set; }
        public int? VendorVatId { get; set; }
        public string NotePayment { get; set; }
        public string Note { get; set; }
        public decimal Cp1 { get; set; }
        public decimal Cp2 { get; set; }
        public bool IsPayment { get; set; }
        public string Notes { get; set; }
        public string PaymentNote { get; set; }
        public string PaymentReturnNote { get; set; }
        public bool IsBet { get; set; }
        public bool IsReturn { get; set; }
        public int? TransportationTypeId { get; set; }
        public bool IsWet { get; set; }
        public decimal? InsuranceFeesRate { get; set; }
        public decimal? CommodityValue { get; set; }
        public decimal? InsuranceFeeNoVAT { get; set; }
        public string Name { get; set; }
        public int? CommodityId2 { get; set; }
        public decimal? InsuranceFeesRateVAT { get; set; }
        public decimal? InsuranceFeeVAT { get; set; }
        public int? CompanyId { get; set; }
        public int? StaffId { get; set; }
        public string NoteReturnReport { get; set; }
        public string TotalWeightReport { get; set; }
        public bool Active { get; set; }
        public int? MovingTypeId { get; set; }
        public DateTime InsertedDate { get; set; }
        public int InsertedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public bool IsBought { get; set; }
        public string InsuranceFeeNotes { get; set; }
        public decimal? BetFee { get; set; }
        public bool ISIncluded { get; set; }
        public decimal? CustomerReturnFee { get; set; }
        public decimal? BetAmount { get; set; }
        public DateTime? DateBetReturnAccountant { get; set; }
        public DateTime? DateBetReturnBrandShip { get; set; }
        public DateTime? DateBetRefunded { get; set; }
        public string DeliveryBetNotes { get; set; }
        public int? LevelId { get; set; }
        public decimal? TotalBet { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
        public string Note3 { get; set; }
        public string Note4 { get; set; }
        public decimal? ReturnLiftFeeReport { get; set; }
        public decimal? ReturnClosingFeeReport { get; set; }
        public string CommodityValueNotes { get; set; }
        public int? JourneyId { get; set; }
        public int? CustomerTypeId { get; set; }
        public decimal? WareHouseUnitPrice { get; set; }
        public bool IsPurchasedInsurance { get; set; }
        public DateTime? DatePurchasedInsurance { get; set; }
        public int? ReturnId2 { get; set; }
        public string NoteReturnReport2 { get; set; }
        public decimal? TotalPriceTaxClosing { get; set; }
        public decimal? TotalPriceNoTaxClosing { get; set; }
        public decimal? TotalCOBNoTaxClosing { get; set; }
        public decimal? TotalCOBTaxClosing { get; set; }
        public decimal? TotalPriceTaxReturn { get; set; }
        public decimal? TotalPriceNoTaxReturn { get; set; }
        public decimal? TotalCOBNoTaxReturn { get; set; }
        public decimal? TotalCOBTaxReturn { get; set; }
        public bool IsQuotation { get; set; }
        public bool IsQuotationReturn { get; set; }
        public decimal? DoVsLiftUnitPrice { get; set; }
        public bool IsHost { get; set; }
        public bool IsBooking { get; set; }
        public bool IsSplitBill { get; set; }
        public string ReturnNotes2 { get; set; }
        public string FreeText { get; set; }
        public string FreeText1 { get; set; }
        public string FreeText2 { get; set; }
        public string FreeText3 { get; set; }
        public string FreeText4 { get; set; }
        public string FreeText5 { get; set; }
        public string FreeText6 { get; set; }
        public string FreeText7 { get; set; }
        public string FreeText8 { get; set; }
        public string FreeText9 { get; set; }
        public bool IsNote { get; set; }
        public int? ContactId { get; set; }
        public int? Contact2Id { get; set; }
        public string MonthText { get; set; }
        public string YearText { get; set; }
        public int? BookingListId { get; set; }
        public int? UserReturnId { get; set; }
        public decimal? CollectOnSupPrice { get; set; }
        public bool IsSeftPayment { get; set; }
        public bool IsSeftPaymentReturn { get; set; }
        public DateTime? ClosingDateCheck { get; set; }
        public string ReceivedCheck { get; set; }
        public string SealCheck { get; set; }
        public string BossCheck { get; set; }
        public int? Cont20Check { get; set; }
        public int? Cont40Check { get; set; }
        public string PickupEmptyCheck { get; set; }
        public string PortLoadingCheck { get; set; }
        public decimal? LiftFeeCheck { get; set; }
        public decimal? LandingFeeCheck { get; set; }
        public decimal? CollectOnBehaftInvoinceNoFeeCheck { get; set; }
        public decimal? CollectOnBehaftFeeCheck { get; set; }
        public decimal? CollectOnSupPriceCheck { get; set; }
        public decimal? ClosingCombinationUnitPriceCheck { get; set; }
        public decimal? ClosingPercentCheck { get; set; }
        public decimal? TotalPriceAfterTaxCheck { get; set; }
        public string ContainerNoCheck { get; set; }
        public bool IsSeftPaymentLand { get; set; }
        public bool IsSeftPaymentLandReturn { get; set; }
        public DateTime? ClosingDateReturnCheck { get; set; }
        public string ReceivedReturnCheck { get; set; }
        public string SealReturnCheck { get; set; }
        public string BossReturnCheck { get; set; }
        public int? Cont20ReturnCheck { get; set; }
        public int? Cont40ReturnCheck { get; set; }
        public string PickupEmptyReturnCheck { get; set; }
        public string PortLoadingReturnCheck { get; set; }
        public decimal? LiftFeeReturnCheck { get; set; }
        public decimal? LandingFeeReturnCheck { get; set; }
        public decimal? CollectOnBehaftInvoinceNoFeeReturnCheck { get; set; }
        public decimal? CollectOnBehaftFeeReturnCheck { get; set; }
        public decimal? CollectOnSupPriceReturnCheck { get; set; }
        public decimal? ClosingCombinationUnitPriceReturnCheck { get; set; }
        public decimal? ClosingPercentReturnCheck { get; set; }
        public decimal? TotalPriceAfterTaxReturnCheck { get; set; }
        public string ContainerNoReturnCheck { get; set; }
        public int? RequestClosing { get; set; }
        public DateTime? ClosingDateUpload { get; set; }
        public string ReceivedCheckUpload { get; set; }
        public string SealCheckUpload { get; set; }
        public string BossCheckUpload { get; set; }
        public int? Cont20CheckUpload { get; set; }
        public int? Cont40CheckUpload { get; set; }
        public string PickupEmptyUpload { get; set; }
        public string PortLoadingUpload { get; set; }
        public decimal? LiftFeeCheckUpload { get; set; }
        public decimal? LandingFeeUpload { get; set; }
        public decimal? CollectOnBehaftInvoinceNoFeeUpload { get; set; }
        public decimal? CollectOnBehaftFeeUpload { get; set; }
        public decimal? CollectOnSupPriceUpload { get; set; }
        public decimal? ClosingCombinationUnitPriceUpload { get; set; }
        public decimal? ClosingPercentUpload { get; set; }
        public decimal? TotalPriceAfterTaxUpload { get; set; }
        public string ContainerNoUpload { get; set; }
        public bool IsLocked { get; set; }
        public bool IsRequestUnLockAll { get; set; }
        public bool IsRequestUnLockExploit { get; set; }
        public bool IsRequestUnLockAccountant { get; set; }
        public bool IsRequestUnLockShip { get; set; }
        public string ReasonUnLockAll { get; set; }
        public string ReasonUnLockExploit { get; set; }
        public string ReasonUnLockAccountant { get; set; }
        public string ReasonUnLockShip { get; set; }
        public int? CheckFeeHistoryId { get; set; }
        public int? ClosingUser { get; set; }
        public int? ReturnUser { get; set; }
        public int? SaleId { get; set; }
        public decimal? FeeVat1 { get; set; }
        public decimal? FeeVat2 { get; set; }
        public decimal? FeeVat3 { get; set; }
        public decimal? Fee1 { get; set; }
        public decimal? Fee2 { get; set; }
        public decimal? Fee3 { get; set; }
        public decimal? Fee4 { get; set; }
        public decimal? Fee5 { get; set; }
        public decimal? Fee6 { get; set; }
        public decimal? Fee1Upload { get; set; }
        public decimal? Fee2Upload { get; set; }
        public decimal? Fee3Upload { get; set; }
        public decimal? Fee4Upload { get; set; }
        public decimal? Fee5Upload { get; set; }
        public decimal? Fee6Upload { get; set; }
        public decimal? FeeVat1Upload { get; set; }
        public decimal? FeeVat2Upload { get; set; }
        public decimal? FeeVat3Upload { get; set; }

        public virtual ICollection<Expense> Expense { get; set; }
        public virtual ICollection<Revenue> Revenue { get; set; }
    }
}
