-- PostgreSQL Schema for CRM Database
-- Converted from SQL Server (T-SQL) with PostgreSQL best practices

-- Dictionary table
CREATE TABLE IF NOT EXISTS dictionary (
    id varchar(50) NOT NULL,
    lang_code varchar(250),
    key varchar(250),
    value varchar(250),
    active boolean NOT NULL,
    inserted_by varchar(50),
    inserted_date timestamptz,
    updated_by varchar(50),
    updated_date timestamptz,
    PRIMARY KEY (id)
);

-- FileUpload table
CREATE TABLE IF NOT EXISTS file_upload (
    id varchar(50) NOT NULL,
    entity_name varchar(250),
    record_id varchar(50),
    section_id varchar(50),
    field_name varchar(100),
    file_name varchar(400),
    file_path varchar(400),
    active boolean NOT NULL,
    inserted_date timestamptz,
    inserted_by varchar(50),
    updated_date timestamptz,
    updated_by varchar(50),
    PRIMARY KEY (id)
);

-- History table
CREATE TABLE IF NOT EXISTS history (
    id varchar(50) NOT NULL,
    text_content text,
    value text,
    old_value text,
    component_id varchar(50),
    record_id varchar(50),
    table_name varchar(250),
    active boolean NOT NULL,
    inserted_date timestamptz,
    inserted_by varchar(50),
    updated_date timestamptz,
    updated_by varchar(50),
    created_by varchar(255),
    PRIMARY KEY (id)
);

-- MasterData table
CREATE TABLE IF NOT EXISTS master_data (
    id varchar(50) NOT NULL,
    code varchar(500),
    name varchar(500),
    description varchar(500),
    parent_id varchar(50),
    path varchar(1000),
    is_local boolean NOT NULL DEFAULT false,
    is_container boolean NOT NULL DEFAULT false,
    is_cbm boolean NOT NULL DEFAULT false,
    is_kgs boolean NOT NULL DEFAULT false,
    is_gw boolean NOT NULL DEFAULT false,
    active boolean NOT NULL DEFAULT false,
    inserted_date timestamptz,
    inserted_by varchar(50),
    updated_date timestamptz,
    updated_by varchar(50),
    enum int,
    group_enum int,
    code_mn varchar(150),
    PRIMARY KEY (id)
);

-- Partner table
CREATE TABLE IF NOT EXISTS partner (
    id varchar(50) NOT NULL,
    service_id int,
    type_id int,
    name varchar(500),
    full_name varchar(500),
    debit_name varchar(500),
    address varchar(500),
    phone_number varchar(50),
    mail varchar(200),
    active boolean NOT NULL,
    inserted_date timestamptz,
    inserted_by varchar(50),
    updated_date timestamptz,
    updated_by varchar(50),
    code varchar(250),
    tax_code varchar(250),
    group_id varchar(50),
    gender_id varchar(50),
    issued_date timestamptz,
    note varchar(500),
    gender_contact_id varchar(50),
    contact_name varchar(500),
    contact_email varchar(255),
    contact_phone_number varchar(50),
    debit_day int,
    debit_amount numeric(19,4),
    credit_limit numeric(19,4),
    debit_account_id varchar(50),
    is_public boolean NOT NULL,
    web varchar(255),
    seq_key int,
    sale_id varchar(50),
    attachment varchar(500),
    email varchar(255),
    source_id varchar(50),
    rating_id varchar(50),
    dob timestamptz,
    pic_id varchar(50),
    customer_type_id varchar(500),
    company_name varchar(500),
    residence_type_id varchar(50),
    residence_type_id_text varchar(500),
    description varchar(500),
    company_name_inv varchar(500),
    email_inv varchar(255),
    assignment_debit_id varchar(50),
    assignment_inv_id varchar(50),
    account_number varchar(50),
    account_name varchar(255),
    bank_id varchar(50),
    account_branch varchar(250),
    swift_code varchar(50),
    opened_at varchar(250),
    id_code varchar(50),
    password varchar(255),
    industry varchar(255),
    po varchar(255),
    rush_month int,
    rating varchar(255),
    po_date timestamptz,
    min_profit_month numeric(19,4),
    toast_warning varchar(255),
    action_id int,
    regular_shipping_from varchar(255),
    condition_id varchar(50),
    distribute_information_ids varchar(255),
    distribute_information_ids_text varchar(255),
    zip_code varchar(50),
    tracking_url varchar(50),
    is_no_debt boolean NOT NULL,
    partner_type_ids varchar(255),
    partner_type_ids_text varchar(255),
    format_chat varchar(250),
    address_inv varchar(250),
    assign_id varchar(50),
    history varchar(500),
    birthday timestamptz,
    logo varchar(500),
    web_site varchar(500),
    fax varchar(50),
    receives_account_number varchar(50),
    receives_account_name varchar(255),
    receives_bank_id varchar(50),
    receives_swift_code varchar(50),
    customer_type_id_text varchar(255),
    feature_name varchar(500),
    header varchar(4000),
    footer varchar(4000),
    PRIMARY KEY (id)
);

-- Role table
CREATE TABLE IF NOT EXISTS role (
    id varchar(50) NOT NULL,
    hidden boolean NOT NULL DEFAULT false,
    name varchar(250),
    description varchar(250),
    active boolean NOT NULL DEFAULT false,
    inserted_by varchar(50),
    inserted_date timestamptz,
    updated_by varchar(50),
    updated_date timestamptz,
    created_by varchar(255),
    PRIMARY KEY (id)
);

-- Tenant table (fixed typo: Tanent → tenant)
CREATE TABLE IF NOT EXISTS tenant (
    id varchar(50) NOT NULL,
    password varchar(250),
    company_name varchar(250),
    tax_code varchar(250),
    tenant_code varchar(250),
    active boolean NOT NULL,
    inserted_by varchar(50),
    inserted_date timestamptz,
    updated_by varchar(50),
    updated_date timestamptz,
    PRIMARY KEY (id)
);

-- TaskNotification table
CREATE TABLE IF NOT EXISTS task_notification (
    id varchar(50) NOT NULL,
    read boolean NOT NULL DEFAULT false,
    icon varchar(150),
    assigned_id varchar(50),
    entity_id varchar(250),
    avatar varchar(2500),
    from_name varchar(2500),
    feature_name varchar(500),
    feature_name_2 varchar(500),
    feature_name_3 varchar(500),
    title varchar(2500),
    title_2 varchar(2500),
    description varchar(2500),
    description_2 varchar(2500),
    active boolean NOT NULL DEFAULT false,
    inserted_date timestamptz,
    inserted_by varchar(50),
    updated_date timestamptz,
    updated_by varchar(50),
    record_id varchar(50),
    voucher_type_id int,
    PRIMARY KEY (id)
);

-- User table
CREATE TABLE IF NOT EXISTS users (
    id varchar(50) NOT NULL,
    code varchar(250),
    email varchar(250),
    password varchar(250),
    salt varchar(250),
    user_name varchar(250),
    full_name varchar(250),
    address varchar(250),
    avatar varchar(250),
    ssn varchar(250),
    phone_number varchar(250),
    team_id varchar(50),
    partner_id varchar(50),
    active boolean NOT NULL DEFAULT false,
    inserted_by varchar(50),
    inserted_date timestamptz,
    updated_by varchar(50),
    updated_date timestamptz,
    dob timestamptz,
    gender_id varchar(50),
    ssn_date timestamptz,
    tax_code varchar(50),
    seq_key int,
    login_failed_count int,
    last_failed_login timestamptz,
    last_login timestamptz,
    recover varchar(500),
    joint_date timestamptz,
    role_ids varchar(500),
    role_ids_text varchar(500),
    department_id varchar(50),
    identity_card_date timestamptz,
    identity_card varchar(150),
    place_issue varchar(150),
    nick_name varchar(150),
    knowledge varchar(150),
    target_local_curr numeric(19,4),
    target_usd_curr numeric(19,4),
    type_bonus_id varchar(50),
    salary_amount numeric(19,4),
    salary_coefficient numeric(19,4),
    insurance_amount numeric(19,4),
    type_contract_id varchar(50),
    dependents int,
    acc_number varchar(50),
    acc_name varchar(255),
    bank_id varchar(50),
    pass_email varchar(255),
    company_id varchar(50),
    is_department boolean NOT NULL DEFAULT false,
    is_team boolean NOT NULL DEFAULT false,
    position_id varchar(50),
    type_id int,
    mail_server varchar(250),
    port_server varchar(250),
    PRIMARY KEY (id)
);

-- UserLogin table
CREATE TABLE IF NOT EXISTS user_login (
    id varchar(50) NOT NULL,
    user_id varchar(50),
    access_token varchar(1500),
    refresh_token varchar(1500),
    access_token_exp timestamptz,
    refresh_token_exp timestamptz,
    active boolean NOT NULL DEFAULT false,
    inserted_by varchar(50),
    inserted_date timestamptz,
    updated_by varchar(50),
    updated_date timestamptz,
    created_by varchar(255),
    ip_address varchar(255),
    PRIMARY KEY (id)
);

-- UserRole table
CREATE TABLE IF NOT EXISTS user_role (
    id varchar(50) NOT NULL,
    user_id varchar(50),
    role_id varchar(50),
    active boolean NOT NULL DEFAULT false,
    inserted_by varchar(50),
    inserted_date timestamptz,
    updated_by varchar(50),
    updated_date timestamptz,
    created_by varchar(255),
    PRIMARY KEY (id)
);

-- UserSetting table
CREATE TABLE IF NOT EXISTS user_setting (
    id varchar(50) NOT NULL,
    feature_id varchar(50),
    component_id varchar(50),
    user_id varchar(50),
    value text,
    active boolean NOT NULL DEFAULT false,
    inserted_date timestamptz,
    inserted_by varchar(50),
    updated_date timestamptz,
    updated_by varchar(50),
    PRIMARY KEY (id)
);