// <auto-generated />
using System;
using CoreAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreAPI.Migrations._202511
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251126074955_InitialUserLogin")]
    partial class InitialUserLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.Component", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("AddDate")
                        .HasColumnType("boolean");

                    b.Property<string>("AddRowExp")
                        .HasColumnType("text");

                    b.Property<int?>("BadgeMonth")
                        .HasColumnType("integer");

                    b.Property<bool>("BasicSearch")
                        .HasColumnType("boolean");

                    b.Property<int?>("BodyItemHeight")
                        .HasColumnType("integer");

                    b.Property<bool>("CanAdd")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanCache")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSearch")
                        .HasColumnType("boolean");

                    b.Property<string>("ChildStyle")
                        .HasColumnType("text");

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<string>("CodeId")
                        .HasColumnType("text");

                    b.Property<int?>("Column")
                        .HasColumnType("integer");

                    b.Property<string>("ComponentDefaultValueId")
                        .HasColumnType("text");

                    b.Property<string>("ComponentGroupId")
                        .HasColumnType("text");

                    b.Property<string>("ComponentId")
                        .HasColumnType("text");

                    b.Property<string>("ComponentType")
                        .HasColumnType("text");

                    b.Property<string>("Css")
                        .HasColumnType("text");

                    b.Property<string>("DatabaseName")
                        .HasColumnType("text");

                    b.Property<string>("DateTimeField")
                        .HasColumnType("text");

                    b.Property<int?>("DefaultAddEnd")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultAddStart")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultVal")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<string>("DisabledExp")
                        .HasColumnType("text");

                    b.Property<bool>("DisplayBadge")
                        .HasColumnType("boolean");

                    b.Property<bool>("Editable")
                        .HasColumnType("boolean");

                    b.Property<string>("EntityId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EntityName")
                        .HasColumnType("text");

                    b.Property<string>("Events")
                        .HasColumnType("text");

                    b.Property<string>("ExcelFieldName")
                        .HasColumnType("text");

                    b.Property<string>("ExcelUrl")
                        .HasColumnType("text");

                    b.Property<string>("FeatureId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FieldName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("FilterEq")
                        .HasColumnType("boolean");

                    b.Property<bool>("FilterLocal")
                        .HasColumnType("boolean");

                    b.Property<string>("FilterTemplate")
                        .HasColumnType("text");

                    b.Property<bool>("Focus")
                        .HasColumnType("boolean");

                    b.Property<bool>("FocusSearch")
                        .HasColumnType("boolean");

                    b.Property<int?>("FooterHeight")
                        .HasColumnType("integer");

                    b.Property<string>("FormatData")
                        .HasColumnType("text");

                    b.Property<string>("FormatExcell")
                        .HasColumnType("text");

                    b.Property<string>("FormatSumaryField")
                        .HasColumnType("text");

                    b.Property<bool>("Frozen")
                        .HasColumnType("boolean");

                    b.Property<string>("GroupBy")
                        .HasColumnType("text");

                    b.Property<string>("GroupEvent")
                        .HasColumnType("text");

                    b.Property<string>("GroupFormat")
                        .HasColumnType("text");

                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.Property<string>("GroupReferenceId")
                        .HasColumnType("text");

                    b.Property<string>("GroupReferenceName")
                        .HasColumnType("text");

                    b.Property<string>("GroupTypeId")
                        .HasColumnType("text");

                    b.Property<bool>("HasFilter")
                        .HasColumnType("boolean");

                    b.Property<int?>("HeaderHeight")
                        .HasColumnType("integer");

                    b.Property<bool>("HideGrid")
                        .HasColumnType("boolean");

                    b.Property<string>("HotKey")
                        .HasColumnType("text");

                    b.Property<string>("Html")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int?>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCollapsible")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDropDown")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMultiple")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRealtime")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSumary")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTab")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVertialTab")
                        .HasColumnType("boolean");

                    b.Property<string>("Javascript")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Lang")
                        .HasColumnType("text");

                    b.Property<int?>("LgCol")
                        .HasColumnType("integer");

                    b.Property<int?>("LgOuterColumn")
                        .HasColumnType("integer");

                    b.Property<string>("ListClass")
                        .HasColumnType("text");

                    b.Property<bool>("LiteGrid")
                        .HasColumnType("boolean");

                    b.Property<string>("MaxWidth")
                        .HasColumnType("text");

                    b.Property<string>("Migration")
                        .HasColumnType("text");

                    b.Property<string>("MinWidth")
                        .HasColumnType("text");

                    b.Property<int?>("MonthCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Offset")
                        .HasColumnType("integer");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("OrderBy")
                        .HasColumnType("text");

                    b.Property<string>("OrderBySumary")
                        .HasColumnType("text");

                    b.Property<int?>("OuterColumn")
                        .HasColumnType("integer");

                    b.Property<string>("ParentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlainText")
                        .HasColumnType("text");

                    b.Property<string>("PopulateField")
                        .HasColumnType("text");

                    b.Property<string>("PreQuery")
                        .HasColumnType("text");

                    b.Property<int?>("Precision")
                        .HasColumnType("integer");

                    b.Property<string>("Query")
                        .HasColumnType("text");

                    b.Property<string>("RefClass")
                        .HasColumnType("text");

                    b.Property<string>("RefName")
                        .HasColumnType("text");

                    b.Property<int?>("ReportTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("Responsive")
                        .HasColumnType("boolean");

                    b.Property<int?>("Row")
                        .HasColumnType("integer");

                    b.Property<int?>("RowSpan")
                        .HasColumnType("integer");

                    b.Property<string>("ScriptValidation")
                        .HasColumnType("text");

                    b.Property<int?>("ScrollHeight")
                        .HasColumnType("integer");

                    b.Property<string>("ShortDesc")
                        .HasColumnType("text");

                    b.Property<bool>("ShowDatetimeField")
                        .HasColumnType("boolean");

                    b.Property<string>("ShowExp")
                        .HasColumnType("text");

                    b.Property<bool>("ShowHotKey")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowLabel")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowNull")
                        .HasColumnType("boolean");

                    b.Property<int?>("SmCol")
                        .HasColumnType("integer");

                    b.Property<int?>("SmOuterColumn")
                        .HasColumnType("integer");

                    b.Property<string>("Style")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int?>("SummaryColSpan")
                        .HasColumnType("integer");

                    b.Property<string>("TabGroup")
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .HasColumnType("text");

                    b.Property<string>("Template")
                        .HasColumnType("text");

                    b.Property<string>("TenantCode")
                        .HasColumnType("text");

                    b.Property<string>("TextAlign")
                        .HasColumnType("text");

                    b.Property<bool>("TopEmpty")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UpperCase")
                        .HasColumnType("boolean");

                    b.Property<string>("Validation")
                        .HasColumnType("text");

                    b.Property<bool>("VirtualScroll")
                        .HasColumnType("boolean");

                    b.Property<bool>("Visibility")
                        .HasColumnType("boolean");

                    b.Property<string>("Width")
                        .HasColumnType("text");

                    b.Property<int?>("XlCol")
                        .HasColumnType("integer");

                    b.Property<int?>("XlOuterColumn")
                        .HasColumnType("integer");

                    b.Property<int?>("XsCol")
                        .HasColumnType("integer");

                    b.Property<int?>("XsOuterColumn")
                        .HasColumnType("integer");

                    b.Property<int?>("XxlCol")
                        .HasColumnType("integer");

                    b.Property<int?>("XxlOuterColumn")
                        .HasColumnType("integer");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Component", (string)null);
                });

            modelBuilder.Entity("Core.Models.Entity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("AliasFor")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Namespace")
                        .HasColumnType("text");

                    b.Property<string>("RefDetailClass")
                        .HasColumnType("text");

                    b.Property<string>("RefListClass")
                        .HasColumnType("text");

                    b.Property<string>("TenantCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Entity", (string)null);
                });

            modelBuilder.Entity("Core.Models.Feature", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<string>("CodeId")
                        .HasColumnType("text");

                    b.Property<bool>("CustomNextCell")
                        .HasColumnType("boolean");

                    b.Property<bool>("DeleteTemp")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Events")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IgnoreEncode")
                        .HasColumnType("boolean");

                    b.Property<bool>("InheritParentFeature")
                        .HasColumnType("boolean");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDevider")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFlow")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLock")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMenu")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("LoadEntity")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("ParentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Script")
                        .HasColumnType("text");

                    b.Property<bool>("StartUp")
                        .HasColumnType("boolean");

                    b.Property<string>("Style")
                        .HasColumnType("text");

                    b.Property<string>("StyleSheet")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ViewClass")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Feature", (string)null);
                });

            modelBuilder.Entity("Core.Models.FeaturePolicy", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanCopy")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanCopyAll")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDeactivate")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDeactivateAll")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDeleteAll")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanReadAll")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanWrite")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanWriteAll")
                        .HasColumnType("boolean");

                    b.Property<string>("FeatureId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecordId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TableName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FeaturePolicy", (string)null);
                });

            modelBuilder.Entity("Core.Models.MasterData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Enum")
                        .HasColumnType("integer");

                    b.Property<int?>("GroupEnum")
                        .HasColumnType("integer");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ParentId")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MasterData");
                });

            modelBuilder.Entity("Core.Models.Partner", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AccName")
                        .HasColumnType("text");

                    b.Property<string>("AccNumber")
                        .HasColumnType("text");

                    b.Property<int?>("ActionId")
                        .HasColumnType("integer");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("AdditionTypeIds")
                        .HasColumnType("text");

                    b.Property<string>("AdditionTypeIdsText")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AddressInv")
                        .HasColumnType("text");

                    b.Property<string>("AssignId")
                        .HasColumnType("text");

                    b.Property<string>("AssignmentDebitId")
                        .HasColumnType("text");

                    b.Property<string>("AssignmentInvId")
                        .HasColumnType("text");

                    b.Property<string>("Attachment")
                        .HasColumnType("text");

                    b.Property<string>("BankId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("CompanyNameInv")
                        .HasColumnType("text");

                    b.Property<string>("ConditionId")
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("CustomerTypeId")
                        .HasColumnType("text");

                    b.Property<string>("DebitAccountId")
                        .HasColumnType("text");

                    b.Property<decimal?>("DebitAmount")
                        .HasColumnType("numeric");

                    b.Property<int?>("DebitDay")
                        .HasColumnType("integer");

                    b.Property<string>("DebitName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DistributeInformationIds")
                        .HasColumnType("text");

                    b.Property<string>("DistributeInformationIdsText")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EmailInv")
                        .HasColumnType("text");

                    b.Property<string>("Footer")
                        .HasColumnType("text");

                    b.Property<string>("FormatChat")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("GenderContactId")
                        .HasColumnType("text");

                    b.Property<string>("GenderId")
                        .HasColumnType("text");

                    b.Property<string>("GroupId")
                        .HasColumnType("text");

                    b.Property<string>("Header")
                        .HasColumnType("text");

                    b.Property<string>("History")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("IdCode")
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsNoDebt")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("IssuedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("Mail")
                        .HasColumnType("text");

                    b.Property<decimal?>("MinProfitMonth")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("PartnerTypeIds")
                        .HasColumnType("text");

                    b.Property<string>("PartnerTypeIdsText")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PicId")
                        .HasColumnType("text");

                    b.Property<string>("Po")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PoDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RaitingId")
                        .HasColumnType("text");

                    b.Property<string>("Rating")
                        .HasColumnType("text");

                    b.Property<string>("RegularShippingFrom")
                        .HasColumnType("text");

                    b.Property<string>("ResidenceTypeId")
                        .HasColumnType("text");

                    b.Property<int?>("RushMonth")
                        .HasColumnType("integer");

                    b.Property<string>("SaleId")
                        .HasColumnType("text");

                    b.Property<int?>("SeqKey")
                        .HasColumnType("integer");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("SourseId")
                        .HasColumnType("text");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("text");

                    b.Property<string>("TaxCode")
                        .HasColumnType("text");

                    b.Property<string>("TrackingURL")
                        .HasColumnType("text");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Warning")
                        .HasColumnType("text");

                    b.Property<string>("Web")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Partner", (string)null);
                });

            modelBuilder.Entity("Core.Models.Resource", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("Annonymous")
                        .HasColumnType("boolean");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Path")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TenantCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Resource", (string)null);
                });

            modelBuilder.Entity("Core.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Core.Models.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.Property<string>("ConnKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ConnStr")
                        .HasColumnType("text");

                    b.Property<string>("Css")
                        .HasColumnType("text");

                    b.Property<string>("Env")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubTenant")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SvcId")
                        .HasColumnType("text");

                    b.Property<string>("Template")
                        .HasColumnType("text");

                    b.Property<string>("TenantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantCode")
                        .IsUnique();

                    b.ToTable("Tenant", (string)null);
                });

            modelBuilder.Entity("Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AccName")
                        .HasColumnType("text");

                    b.Property<string>("AccNumber")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("BankId")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("text");

                    b.Property<int?>("Dependents")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("GenderId")
                        .HasColumnType("text");

                    b.Property<string>("IdentityCard")
                        .HasColumnType("text");

                    b.Property<DateTime?>("IdentityCardDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("InsuranceAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<bool>("IsDepartment")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTeam")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("JointDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Knowledge")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastFailedLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LoginFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("MailServer")
                        .HasColumnType("text");

                    b.Property<string>("NickName")
                        .HasColumnType("text");

                    b.Property<string>("PartnerId")
                        .HasColumnType("text");

                    b.Property<string>("PassEmail")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlaceIssue")
                        .HasColumnType("text");

                    b.Property<string>("PortServer")
                        .HasColumnType("text");

                    b.Property<string>("PositionId")
                        .HasColumnType("text");

                    b.Property<string>("Recover")
                        .HasColumnType("text");

                    b.Property<string>("RoleIds")
                        .HasColumnType("text");

                    b.Property<string>("RoleIdsText")
                        .HasColumnType("text");

                    b.Property<decimal?>("SalaryAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SalaryCoefficient")
                        .HasColumnType("numeric");

                    b.Property<string>("Salt")
                        .HasColumnType("text");

                    b.Property<int?>("SeqKey")
                        .HasColumnType("integer");

                    b.Property<string>("Ssn")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SsnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("TargetLocalCurr")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TargetUSDCurr")
                        .HasColumnType("numeric");

                    b.Property<string>("TaxCode")
                        .HasColumnType("text");

                    b.Property<string>("TeamId")
                        .HasColumnType("text");

                    b.Property<string>("TypeBonusId")
                        .HasColumnType("text");

                    b.Property<string>("TypeContractId")
                        .HasColumnType("text");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("UserName");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Core.Models.UserLogin", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AccessTokenExp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin", (string)null);
                });

            modelBuilder.Entity("Core.Models.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantCode")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("Core.Models.UserSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("ComponentId")
                        .HasColumnType("text");

                    b.Property<string>("FeatureId")
                        .HasColumnType("text");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserSetting", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
