CREATE TABLE [dbo].[Accessory] (
    [Id]                      INT             IDENTITY (1, 1) NOT NULL,
    [TruckId]                 INT             NULL,
    [BranchId]                INT             NULL,
    [Name]                    NVARCHAR (100)  NULL,
    [Version]                 NVARCHAR (100)  NULL,
    [VendorId]                INT             NULL,
    [Price]                   DECIMAL (20, 5) NOT NULL,
    [CurrencyId]              INT             NULL,
    [AssembledDate]           DATETIME2 (7)   NOT NULL,
    [ExpiredDate]             DATETIME2 (7)   NULL,
    [MaintenancePeriod]       BIGINT          NULL,
    [NextMaintenanceDate]     DATETIME2 (7)   NULL,
    [PaymentMethodId]         INT             NULL,
    [ExchangeRate]            DECIMAL (20, 5) NOT NULL,
    [IsOriginal]              BIT             NOT NULL,
    [Paid]                    BIT             CONSTRAINT [DF__Accessory__Paid__74AE54BC] DEFAULT ((0)) NOT NULL,
    [InitOdoKm]               DECIMAL (20, 5) NOT NULL,
    [ExpiredKm]               DECIMAL (20, 5) NULL,
    [DepreciationCreditAccId] INT             NULL,
    [DepreciationDebitAccId]  INT             NULL,
    [Image]                   NVARCHAR (300)  NULL,
    [UomId]                   INT             NULL,
    [Quantity]                DECIMAL (20, 5) NOT NULL,
    [RootAccessoryId]         INT             NULL,
    [DerivedMaintenanceId]    INT             NULL,
    [DepreciationCoefficient] DECIMAL (4, 2)  CONSTRAINT [DF__Accessory__Coeff__208DA251] DEFAULT ((1)) NOT NULL,
    [DepreciationMethodId]    INT             NULL,
    [Active]                  BIT             NOT NULL,
    [InsertedDate]            DATETIME2 (7)   NOT NULL,
    [InsertedBy]              INT             NOT NULL,
    [UpdatedDate]             DATETIME2 (7)   NULL,
    [UpdatedBy]               INT             NULL,
    [TanentId]                INT             NOT NULL,
    CONSTRAINT [PK_Accessory] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Accessory_Truck] FOREIGN KEY ([TruckId]) REFERENCES [dbo].[Truck] ([Id]),
    CONSTRAINT [FK_Accessory_Vendor] FOREIGN KEY ([VendorId]) REFERENCES [dbo].[Vendor] ([Id])
);

