CREATE TABLE [dbo].[AdvPayment] (
    [Id]                 INT             IDENTITY (1, 1) NOT NULL,
    [CostCenterId]       INT             NULL,
    [PaybackPaymentDate] DATETIME2 (7)   NULL,
    [UserId]             INT             NOT NULL,
    [Amount]             DECIMAL (20, 5) CONSTRAINT [DF_AdvPayment_Amount] DEFAULT ((0)) NOT NULL,
    [CurrencyId]         INT             NOT NULL,
    [ExchangeRate]       DECIMAL (20, 5) CONSTRAINT [DF_AdvPayment_ExchangeRate] DEFAULT ((0)) NOT NULL,
    [PaybackId]          INT             NULL,
    [StatusId]           INT             NULL,
    [IsSend]             BIT             CONSTRAINT [DF_AdvPayment_IsSend] DEFAULT ((0)) NOT NULL,
    [PaymentMethodId]    INT             NULL,
    [Notes]              NVARCHAR (3000) NULL,
    [BankId]             INT             NULL,
    [BankBranchId]       INT             NULL,
    [BankAccountNo]      NVARCHAR (50)   NULL,
    [BankAccountName]    NVARCHAR (50)   NULL,
    [Attachments]        NVARCHAR (3000) NULL,
    [Active]             BIT             NOT NULL,
    [InsertedDate]       DATETIME2 (7)   NOT NULL,
    [InsertedBy]         INT             NOT NULL,
    [UpdatedDate]        DATETIME2 (7)   NULL,
    [UpdatedBy]          INT             NULL,
    [TanentId]           INT             NOT NULL,
    CONSTRAINT [PK_AdvPayment] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AdvPayment_PaybackPayment] FOREIGN KEY ([PaybackId]) REFERENCES [dbo].[PaybackPayment] ([Id]),
    CONSTRAINT [FK_AdvPayment_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([Id])
);

