CREATE TABLE [dbo].[Block] (
    [Id]                    INT             IDENTITY (1, 1) NOT NULL,
    [OrderDetailId]         INT             NOT NULL,
    [BoxLength]             DECIMAL (20, 5) NOT NULL,
    [BoxWidth]              DECIMAL (20, 5) NOT NULL,
    [BoxHeight]             DECIMAL (20, 5) NOT NULL,
    [BoxVolume]             DECIMAL (20, 5) CONSTRAINT [DF_Block_BoxVolume] DEFAULT ((0)) NOT NULL,
    [BoxWeight]             DECIMAL (20, 5) CONSTRAINT [DF_Block_BoxWeight] DEFAULT ((0)) NOT NULL,
    [PackingWeight]         DECIMAL (20, 5) NOT NULL,
    [PackingVolume]         DECIMAL (20, 5) NOT NULL,
    [StackDirectionId]      INT             NULL,
    [TotalBoxVolume]        DECIMAL (20, 5) CONSTRAINT [DF_Block_BoxVolume1] DEFAULT ((0)) NOT NULL,
    [TotalBoxWeight]        DECIMAL (20, 5) CONSTRAINT [DF_Block_BoxWeight1_1] DEFAULT ((0)) NOT NULL,
    [MinStack]              INT             NULL,
    [MaxStack]              INT             NULL,
    [Quantity]              DECIMAL (20, 5) NOT NULL,
    [RemainingQuantity]     DECIMAL (20, 5) NOT NULL,
    [QuantityPacking]       DECIMAL (20, 5) NOT NULL,
    [PriceBeforeTax]        DECIMAL (20, 5) CONSTRAINT [DF__Block__PriceBefo__5E5FEC41] DEFAULT ((0)) NOT NULL,
    [PriceAfterTax]         DECIMAL (20, 5) CONSTRAINT [DF__Block__PriceAfte__5F54107A] DEFAULT ((0)) NOT NULL,
    [CurrencyId]            INT             NULL,
    [ExchangeRate]          DECIMAL (20, 5) NULL,
    [ContainerMovingTypeId] INT             CONSTRAINT [DF_Block_ContainerMovingTypeId] DEFAULT ((0)) NULL,
    [BlockTypeId]           INT             NULL,
    [FromId]                INT             NULL,
    [ToId]                  INT             NULL,
    [Active]                BIT             NOT NULL,
    [InsertedDate]          DATETIME2 (7)   NOT NULL,
    [InsertedBy]            INT             NOT NULL,
    [UpdatedDate]           DATETIME2 (7)   NULL,
    [UpdatedBy]             INT             NULL,
    [TanentId]              INT             NOT NULL,
    CONSTRAINT [PK_Block] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Block_OrderDetail] FOREIGN KEY ([OrderDetailId]) REFERENCES [dbo].[OrderDetail] ([Id])
);

