CREATE TABLE [dbo].[ComponentGroup] (
    [Id]             INT            IDENTITY (1, 1) NOT NULL,
    [FeatureId]      INT            NOT NULL,
    [Name]           NVARCHAR (50)  NULL,
    [Label]          NVARCHAR (50)  NULL,
    [Description]    NVARCHAR (200) NULL,
    [ClassName]      VARCHAR (50)   NULL,
    [IsTab]          BIT            CONSTRAINT [DF_UIGroup_IsTab] DEFAULT ((0)) NOT NULL,
    [TabGroup]       VARCHAR (50)   NULL,
    [IsVertialTab]   BIT            CONSTRAINT [DF_ComponentGroup_IsVertialTab] DEFAULT ((0)) NOT NULL,
    [Events]         VARCHAR (200)  NULL,
    [Width]          VARCHAR (50)   NULL,
    [Style]          VARCHAR (200)  NULL,
    [Column]         INT            NOT NULL,
    [Row]            INT            NOT NULL,
    [PolicyId]       INT            NULL,
    [Hidden]         BIT            NOT NULL,
    [ParentId]       INT            NULL,
    [Order]          INT            NULL,
    [Active]         BIT            NOT NULL,
    [InsertedDate]   DATETIME2 (7)  NOT NULL,
    [InsertedBy]     INT            NOT NULL,
    [UpdatedDate]    DATETIME2 (7)  NULL,
    [UpdatedBy]      INT            NULL,
    [Disabled]       BIT            DEFAULT ((0)) NOT NULL,
    [XsCol]          INT            NULL,
    [SmCol]          INT            NULL,
    [LgCol]          INT            NULL,
    [XlCol]          INT            NULL,
    [XxlCol]         INT            NULL,
    [OuterColumn]    INT            NULL,
    [XsOuterColumn]  INT            NULL,
    [SmOuterColumn]  INT            NULL,
    [LgOuterColumn]  INT            NULL,
    [XlOuterColumn]  INT            NULL,
    [XxlOuterColumn] INT            NULL,
    [TanentId]       INT            NOT NULL,
    [RoleId]         INT            NULL,
    CONSTRAINT [PK_ComponentGroup] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ComponentGroup_ComponentGroup] FOREIGN KEY ([ParentId]) REFERENCES [dbo].[ComponentGroup] ([Id]),
    CONSTRAINT [FK_ComponentGroup_Feature] FOREIGN KEY ([FeatureId]) REFERENCES [dbo].[Feature] ([Id])
);

