CREATE TABLE [dbo].[Component] (
    [Id]               INT             IDENTITY (1, 1) NOT NULL,
    [FieldName]        VARCHAR (50)    NULL,
    [Order]            INT             NULL,
    [ComponentType]    VARCHAR (50)    NOT NULL,
    [ComponentGroupId] INT             NOT NULL,
    [DataSourceFilter] VARCHAR (1000)  NULL,
    [ReferenceId]      INT             NULL,
    [FormatData]       NVARCHAR (250)  NULL,
    [FormatEntity]     NVARCHAR (250)  NULL,
    [PlainText]        NVARCHAR (250)  NULL,
    [Column]           INT             NULL,
    [Offset]           INT             NULL,
    [Row]              INT             NULL,
    [CanSearch]        BIT             NOT NULL,
    [CanCache]         BIT             NOT NULL,
    [Precision]        INT             NULL,
    [GroupBy]          VARCHAR (100)   NULL,
    [GroupFormat]      NVARCHAR (500)  NULL,
    [Label]            NVARCHAR (50)   NULL,
    [ShowLabel]        BIT             NOT NULL,
    [Icon]             VARCHAR (50)    NULL,
    [ClassName]        VARCHAR (50)    NULL,
    [Style]            VARCHAR (200)   NULL,
    [ChildStyle]       VARCHAR (200)   NULL,
    [HotKey]           VARCHAR (50)    NULL,
    [RefClass]         VARCHAR (200)   NULL,
    [Events]           VARCHAR (200)   NULL,
    [Disabled]         BIT             NOT NULL,
    [Visibility]       BIT             NOT NULL,
    [Hidden]           BIT             CONSTRAINT [DF_UserInterface_Hidden] DEFAULT ((0)) NOT NULL,
    [Validation]       NVARCHAR (1000) NULL,
    [Focus]            BIT             NOT NULL,
    [Width]            VARCHAR (20)    NULL,
    [PopulateField]    VARCHAR (100)   NULL,
    [CascadeField]     VARCHAR (50)    NULL,
    [GroupEvent]       VARCHAR (200)   NULL,
    [XsCol]            INT             NULL,
    [SmCol]            INT             NULL,
    [LgCol]            INT             NULL,
    [XlCol]            INT             NULL,
    [XxlCol]           INT             NULL,
    [DefaultVal]       NVARCHAR (100)  NULL,
    [DateTimeField]    VARCHAR (50)    NULL,
    [Active]           BIT             NOT NULL,
    [InsertedDate]     DATETIME2 (7)   NOT NULL,
    [InsertedBy]       INT             NOT NULL,
    [UpdatedDate]      DATETIME2 (7)   NULL,
    [UpdatedBy]        INT             NULL,
    [TanentId]         INT             NOT NULL,
    [RoleId]           INT             NULL,
    CONSTRAINT [PK_Component] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Component_ComponentGroup] FOREIGN KEY ([ComponentGroupId]) REFERENCES [dbo].[ComponentGroup] ([Id]),
    CONSTRAINT [FK_Component_Entity] FOREIGN KEY ([ReferenceId]) REFERENCES [dbo].[Entity] ([Id])
);

