CREATE TABLE [dbo].[Container] (
    [Id]              INT             IDENTITY (1, 1) NOT NULL,
    [VendorId]        INT             NOT NULL,
    [ContainerTypeId] INT             NOT NULL,
    [Code]            VARCHAR (20)    NOT NULL,
    [Description]     NVARCHAR (200)  NULL,
    [FreightStateId]  INT             NULL,
    [MaxCbm]          DECIMAL (20, 5) CONSTRAINT [DF_Container_MaxCbm] DEFAULT ((0)) NOT NULL,
    [MaxWeight]       DECIMAL (20, 5) CONSTRAINT [DF_Container_MaxWeight] DEFAULT ((0)) NOT NULL,
    [RentDate]        DATETIME2 (7)   NULL,
    [EndRentDate]     DATETIME2 (7)   NULL,
    [AdvancedPaid]    DECIMAL (20, 5) NOT NULL,
    [TotalPaid]       DECIMAL (20, 5) NOT NULL,
    [NextPayment]     DATETIME2 (7)   NULL,
    [ApplyPeriod]     BIT             NOT NULL,
    [PeriodPayment]   DECIMAL (20, 5) NOT NULL,
    [CurrencyId]      INT             NULL,
    [InUse]           BIT             CONSTRAINT [DF_Container_IsMaintained] DEFAULT ((0)) NULL,
    [Active]          BIT             NOT NULL,
    [InsertedDate]    DATETIME2 (7)   NOT NULL,
    [InsertedBy]      INT             NOT NULL,
    [UpdatedDate]     DATETIME2 (7)   NULL,
    [UpdatedBy]       INT             NULL,
    [CreditAccId]     INT             NULL,
    [DebitAccId]      INT             NULL,
    [PaymentMethodId] INT             NULL,
    [ExchangeRate]    DECIMAL (20, 5) NOT NULL,
    [TanentId]        INT             NOT NULL,
    CONSTRAINT [PK_Container] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Container_Container1] FOREIGN KEY ([Id]) REFERENCES [dbo].[Container] ([Id]),
    CONSTRAINT [FK_Container_Vendor] FOREIGN KEY ([VendorId]) REFERENCES [dbo].[Vendor] ([Id])
);

