CREATE TABLE [dbo].[Contract] (
    [Id]                INT             IDENTITY (1, 1) NOT NULL,
    [UserId]            INT             NOT NULL,
    [BranchId]          INT             NULL,
    [IsProbation]       BIT             NOT NULL,
    [EffectiveDate]     DATETIME2 (7)   NULL,
    [ExpiredDate]       DATETIME2 (7)   NULL,
    [NetSalary]         DECIMAL (20, 5) NOT NULL,
    [GrossSalary]       DECIMAL (20, 5) NOT NULL,
    [InsuranceSalary]   DECIMAL (20, 5) NOT NULL,
    [Allowance1]        DECIMAL (20, 5) CONSTRAINT [DF_Contract_Allowance] DEFAULT ((0)) NOT NULL,
    [Allowance2]        DECIMAL (20, 5) CONSTRAINT [DF_Contract_Allowance2] DEFAULT ((0)) NOT NULL,
    [Allowance3]        DECIMAL (20, 5) CONSTRAINT [DF_Contract_Allowance3] DEFAULT ((0)) NOT NULL,
    [Allowance4]        DECIMAL (20, 5) CONSTRAINT [DF_Contract_Allowance4] DEFAULT ((0)) NOT NULL,
    [Insurrance1]       DECIMAL (20, 5) CONSTRAINT [DF_Contract_Insurrance1] DEFAULT ((0)) NOT NULL,
    [Insurrance2]       DECIMAL (20, 5) NOT NULL,
    [Insurrance3]       DECIMAL (20, 5) CONSTRAINT [DF_Contract_Insurrance3] DEFAULT ((0)) NOT NULL,
    [Insurrance4]       DECIMAL (20, 5) NOT NULL,
    [AnnualLeave]       DECIMAL (3, 1)  NOT NULL,
    [HolidayLeave]      DECIMAL (3, 1)  NOT NULL,
    [MaternityLeave]    DECIMAL (3, 1)  NOT NULL,
    [SickLeave]         DECIMAL (3, 1)  NOT NULL,
    [ChildrenSickLeave] DECIMAL (3, 1)  NOT NULL,
    [AccidentLeave]     DECIMAL (3, 1)  NOT NULL,
    [MarriageLeave]     DECIMAL (3, 1)  NOT NULL,
    [RelativeLeave]     DECIMAL (3, 1)  NOT NULL,
    [CurrencyId]        INT             CONSTRAINT [DF_Contract_CurrencyId] DEFAULT ((0)) NOT NULL,
    [ExchangeRate]      DECIMAL (20, 5) NULL,
    [Attachment]        NVARCHAR (MAX)  NULL,
    [Active]            BIT             NOT NULL,
    [InsertedDate]      DATETIME2 (7)   NOT NULL,
    [InsertedBy]        INT             NOT NULL,
    [UpdatedDate]       DATETIME2 (7)   NULL,
    [UpdatedBy]         INT             NULL,
    [TanentId]          INT             NOT NULL,
    CONSTRAINT [PK_Contract] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Contract_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([Id])
);

