CREATE TABLE [dbo].[CoordinationDetail] (
    [Id]                        INT             IDENTITY (1, 1) NOT NULL,
    [IsSend]                    BIT             CONSTRAINT [DF_CoordinationDetail_IsSend] DEFAULT ((0)) NOT NULL,
    [IsSendVendor]              BIT             CONSTRAINT [DF_CoordinationDetail_IsSendVendor] DEFAULT ((0)) NOT NULL,
    [BlockTypeId]               INT             NULL,
    [CoordinationId]            INT             NULL,
    [PortOfExportId]            INT             NULL,
    [PortOfImportId]            INT             NULL,
    [PortOfExportName]          NVARCHAR (50)   NULL,
    [PortOfImportName]          NVARCHAR (50)   NULL,
    [CoordinationTypeName]      NVARCHAR (50)   NULL,
    [IsContainer]               BIT             CONSTRAINT [DF_CoordinationDetail_IsContainer] DEFAULT ((0)) NOT NULL,
    [ActualSubmittedDate]       DATETIME2 (7)   NULL,
    [ActualStartDate]           DATETIME2 (7)   NULL,
    [ActualTrailerPlaceDate]    DATETIME2 (7)   NULL,
    [ActualTrailerTakenDate]    DATETIME2 (7)   NULL,
    [ActualContainerPlaceDate]  DATETIME2 (7)   NULL,
    [ActualContainerTakenDate]  DATETIME2 (7)   NULL,
    [ActualGoodsPlaceDate]      DATETIME2 (7)   NULL,
    [ActualGoodsTakenDate]      DATETIME2 (7)   NULL,
    [ActualDeliveredDate]       DATETIME2 (7)   NULL,
    [ActualContainerReturnDate] DATETIME2 (7)   NULL,
    [ActualTrailerReturnDate]   DATETIME2 (7)   NULL,
    [ActualEndDate]             DATETIME2 (7)   NULL,
    [ActualCancelledDate]       DATETIME2 (7)   NULL,
    [ActualPlannedDate]         DATETIME2 (7)   NULL,
    [ActualNonPlanningDate]     DATETIME2 (7)   NULL,
    [ActualDeliveryPlaceDate]   DATETIME2 (7)   NULL,
    [VendorId]                  INT             NULL,
    [OrderDetailId]             INT             NULL,
    [SubVendorId]               INT             NULL,
    [CoordinationTypeId]        INT             NULL,
    [CommodityTypeName]         NVARCHAR (100)  NULL,
    [QuotationId]               INT             NULL,
    [TruckId]                   INT             NULL,
    [TrailerId]                 INT             NULL,
    [TrailerNo]                 VARCHAR (50)    NULL,
    [DriverId]                  INT             NULL,
    [Driver2Id]                 INT             NULL,
    [Driver3Id]                 INT             NULL,
    [ContainerTypeId]           INT             NULL,
    [ContainerId]               INT             NULL,
    [ContainerNo]               VARCHAR (50)    NULL,
    [SealNumbersCont]           NVARCHAR (50)   NULL,
    [ContainerMovingTypeId]     INT             NULL,
    [BookingNo]                 NVARCHAR (50)   NULL,
    [ShippingLineId]            INT             NULL,
    [ReceivedDate]              DATETIME2 (7)   NULL,
    [DeliveryDate]              DATETIME2 (7)   NULL,
    [CutOff]                    DATETIME2 (7)   NULL,
    [FreightStateId]            INT             NULL,
    [FromId]                    INT             NULL,
    [ToId]                      INT             NULL,
    [EmptyContFromId]           INT             NULL,
    [EmptyContToId]             INT             NULL,
    [ContactEmptyContFromId]    INT             NULL,
    [ContactEmptyContToId]      INT             NULL,
    [StartOdo]                  DECIMAL (20, 5) NULL,
    [EndOdo]                    DECIMAL (20, 5) NULL,
    [Note1]                     NVARCHAR (MAX)  NULL,
    [Note]                      NVARCHAR (MAX)  NULL,
    [DriverNote]                NVARCHAR (MAX)  NULL,
    [AllocatedCost]             DECIMAL (20, 5) NULL,
    [AddressGetTrailer]         INT             NULL,
    [AddressReturnTrailer]      INT             NULL,
    [GoodsName]                 NVARCHAR (50)   NULL,
    [CommodityTypeId]           INT             NULL,
    [PriceBeforeTax]            DECIMAL (20, 5) NOT NULL,
    [Vat]                       DECIMAL (20, 5) NOT NULL,
    [PriceAfterTax]             DECIMAL (20, 5) NOT NULL,
    [TotalSurchargeBeforeTax]   DECIMAL (20, 5) CONSTRAINT [DF_CoordinationDetail_TotalSurchargeBeforeTax] DEFAULT ((0.0)) NOT NULL,
    [TotalSurchargeAfterTax]    DECIMAL (20, 5) CONSTRAINT [DF_CoordinationDetail_TotalSurchargeAfterTax] DEFAULT ((0.0)) NOT NULL,
    [SubPriceAfterTax]          DECIMAL (20, 5) NOT NULL,
    [SubPriceBeforeTax]         DECIMAL (20, 5) NOT NULL,
    [SubVat]                    DECIMAL (20, 5) NOT NULL,
    [CurrencyId]                INT             NULL,
    [SubCurrencyId]             INT             NULL,
    [SubExchangeRate]           DECIMAL (20, 5) NOT NULL,
    [ExchangeRate]              DECIMAL (20, 5) NOT NULL,
    [Cost]                      DECIMAL (20, 5) NOT NULL,
    [Profit]                    DECIMAL (20, 5) NOT NULL,
    [Distance]                  DECIMAL (20, 5) NOT NULL,
    [Attachments]               NVARCHAR (MAX)  NULL,
    [Hbl]                       VARCHAR (50)    NULL,
    [RouteId]                   INT             NULL,
    [TruckTypeId]               INT             NULL,
    [BoxTypeId]                 INT             NULL,
    [TruckCbm]                  DECIMAL (20, 5) NOT NULL,
    [TruckWeight]               DECIMAL (20, 5) NOT NULL,
    [TotalCbm]                  DECIMAL (20, 5) NOT NULL,
    [TotalWeight]               DECIMAL (20, 5) NOT NULL,
    [TotalBox]                  DECIMAL (20, 5) NOT NULL,
    [PickupTimeFrom]            NVARCHAR (50)   NULL,
    [PickupTimeTo]              NVARCHAR (50)   NULL,
    [DeliveryTimeFrom]          NVARCHAR (50)   NULL,
    [DeliveryTimeTo]            NVARCHAR (50)   NULL,
    [CustomerId]                INT             NULL,
    [OrderbyDate]               AS              (case [ContainerMovingTypeId] when (2696) then [DeliveryDate] else [ReceivedDate] end) PERSISTED,
    [OrderTime]                 AS              (case [ContainerMovingTypeId] when (2696) then ([PickupTimeFrom]+' - ')+[PickupTimeTo] else ([DeliveryTimeFrom]+' - ')+[DeliveryTimeTo] end),
    [RoleId]                    INT             NULL,
    [RolePath]                  VARCHAR (100)   NULL,
    [AccountableUserId]         INT             NULL,
    [Star]                      INT             NULL,
    [Comment]                   NVARCHAR (100)  NULL,
    [ParkingId]                 INT             NULL,
    [IsParking]                 BIT             NULL,
    [Active]                    BIT             NOT NULL,
    [InsertedDate]              DATETIME2 (7)   NOT NULL,
    [InsertedBy]                INT             NOT NULL,
    [UpdatedDate]               DATETIME2 (7)   NULL,
    [UpdatedBy]                 INT             NULL,
    [Lock]                      BIT             NULL,
    [SubVendorRoleId]           INT             NULL,
    [TanentId]                  INT             NOT NULL,
    CONSTRAINT [PK_CoordinationDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CoordinationDetail_Coordination] FOREIGN KEY ([CoordinationId]) REFERENCES [dbo].[Coordination] ([Id]),
    CONSTRAINT [FK_CoordinationDetail_CoordinationDetail] FOREIGN KEY ([Id]) REFERENCES [dbo].[CoordinationDetail] ([Id]),
    CONSTRAINT [FK_CoordinationDetail_OrderDetail] FOREIGN KEY ([OrderDetailId]) REFERENCES [dbo].[OrderDetail] ([Id]),
    CONSTRAINT [FK_CoordinationDetail_Route] FOREIGN KEY ([RouteId]) REFERENCES [dbo].[Route] ([Id]),
    CONSTRAINT [FK_CoordinationDetail_Trailer] FOREIGN KEY ([TrailerId]) REFERENCES [dbo].[Truck] ([Id]),
    CONSTRAINT [FK_CoordinationDetail_Truck] FOREIGN KEY ([TruckId]) REFERENCES [dbo].[Truck] ([Id]),
    CONSTRAINT [FK_CoordinationDetail_Vendor] FOREIGN KEY ([VendorId]) REFERENCES [dbo].[Vendor] ([Id])
);


GO
CREATE NONCLUSTERED INDEX [IX_OrderDate]
    ON [dbo].[CoordinationDetail]([OrderbyDate] DESC);

