CREATE TABLE [dbo].[CoordinationDetailBlock] (
    [Id]                    INT             IDENTITY (1, 1) NOT NULL,
    [CoordinationDetailId]  INT             NOT NULL,
    [BlockTypeId]           INT             NULL,
    [BlockId]               INT             NOT NULL,
    [ContainerId]           INT             NULL,
    [Quantity]              DECIMAL (10, 2) NOT NULL,
    [RemainingQuantity]     DECIMAL (10, 2) NOT NULL,
    [Residual]              DECIMAL (10, 2) NOT NULL,
    [PriceBeforeTax]        DECIMAL (20, 5) NOT NULL,
    [Vat]                   DECIMAL (4, 2)  NULL,
    [PriceAfterTax]         DECIMAL (20, 5) NOT NULL,
    [SubPriceBeforeTax]     DECIMAL (20, 5) NOT NULL,
    [SubPriceAfterTax]      DECIMAL (20, 5) NOT NULL,
    [CurrencyId]            INT             NULL,
    [ExchangeRate]          DECIMAL (20, 5) CONSTRAINT [DF_CoordinationDetailBlock_ExchangeRate] DEFAULT ((1)) NOT NULL,
    [ContainerMovingTypeId] INT             CONSTRAINT [DF_CoordinationDetailBlock_ContainerMovingTypeId] DEFAULT ((0)) NULL,
    [Volume]                DECIMAL (20, 5) NOT NULL,
    [Weight]                DECIMAL (20, 5) NOT NULL,
    [TotalVolume]           DECIMAL (20, 5) CONSTRAINT [DF_CoordinationDetailBlock_TotalVolume] DEFAULT ((0)) NOT NULL,
    [TotalWeight]           DECIMAL (20, 5) CONSTRAINT [DF_CoordinationDetailBlock_TotalWeight] DEFAULT ((0)) NOT NULL,
    [BoxLength]             DECIMAL (20, 5) CONSTRAINT [DF_CoordinationDetailBlock_BoxLength] DEFAULT ((0)) NOT NULL,
    [BoxWidth]              DECIMAL (20, 5) CONSTRAINT [DF_CoordinationDetailBlock_BoxWidth] DEFAULT ((0)) NOT NULL,
    [BoxHeight]             DECIMAL (20, 5) CONSTRAINT [DF_CoordinationDetailBlock_BoxHeight] DEFAULT ((0)) NOT NULL,
    [Note]                  NVARCHAR (MAX)  NULL,
    [FromId]                INT             NULL,
    [ToId]                  INT             NULL,
    [QuantityBlock]         INT             NULL,
    [Active]                BIT             NOT NULL,
    [InsertedDate]          DATETIME2 (7)   NOT NULL,
    [InsertedBy]            INT             NOT NULL,
    [UpdatedDate]           DATETIME2 (7)   NULL,
    [UpdatedBy]             INT             NULL,
    [TanentId]              INT             NOT NULL,
    CONSTRAINT [PK_CoordinationDetailBlock] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CoordinationDetailBlock_Block] FOREIGN KEY ([BlockId]) REFERENCES [dbo].[Block] ([Id]),
    CONSTRAINT [FK_CoordinationDetailBlock_CoordinationDetail] FOREIGN KEY ([CoordinationDetailId]) REFERENCES [dbo].[CoordinationDetail] ([Id])
);

