CREATE TABLE [dbo].[CustomerCareLog] (
    [Id]                INT             IDENTITY (1, 1) NOT NULL,
    [CustomerId]        INT             NOT NULL,
    [ContactTypeId]     INT             NULL,
    [CustomerContactId] INT             NULL,
    [NumberOfContainer] INT             NULL,
    [ContainerTypeId]   INT             NULL,
    [ContactNumber]     NVARCHAR (50)   NULL,
    [NextMeetingDate]   DATETIME2 (7)   NULL,
    [Volume]            DECIMAL (20, 5) NOT NULL,
    [Weight]            DECIMAL (20, 5) NOT NULL,
    [Distance]          DECIMAL (20, 5) NOT NULL,
    [StatusId]          INT             NULL,
    [QuotationId]       INT             NULL,
    [EstimatedCost]     DECIMAL (20, 5) NOT NULL,
    [Message]           NVARCHAR (MAX)  NULL,
    [IsOfficalContact]  BIT             CONSTRAINT [DF_CustomerCareLog_IsOfficalContact] DEFAULT ((0)) NOT NULL,
    [Active]            BIT             NOT NULL,
    [InsertedDate]      DATETIME2 (7)   NOT NULL,
    [InsertedBy]        INT             NOT NULL,
    [UpdatedDate]       DATETIME2 (7)   NULL,
    [UpdatedBy]         INT             NULL,
    [CommodityTypeId]   INT             NULL,
    [OrderPeriodId]     INT             NULL,
    [ContactDate]       DATETIME2 (7)   NULL,
    [TanentId]          INT             NOT NULL,
    CONSTRAINT [PK_CustomerCareLog] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CustomerCareLog_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Vendor] ([Id]),
    CONSTRAINT [FK_CustomerCareLog_Quotation] FOREIGN KEY ([QuotationId]) REFERENCES [dbo].[Quotation] ([Id])
);

