CREATE TABLE [dbo].[CustomerContact] (
    [Id]            INT            IDENTITY (1, 1) NOT NULL,
    [CustomerId]    INT            NULL,
    [UserId]        INT            NULL,
    [TerminalId]    INT            NULL,
    [Order]         INT            NOT NULL,
    [VendorId]      INT            NULL,
    [FirstName]     NVARCHAR (50)  NULL,
    [LastName]      NVARCHAR (50)  NULL,
    [FullName]      NVARCHAR (50)  NULL,
    [GenderId]      INT            NULL,
    [DoB]           DATETIME2 (7)  NULL,
    [Ssn]           VARCHAR (50)   NULL,
    [Passport]      VARCHAR (50)   NULL,
    [Address]       NVARCHAR (200) NULL,
    [PhoneNumber]   VARCHAR (50)   NULL,
    [PhoneNumber1]  VARCHAR (50)   NULL,
    [Skype]         NVARCHAR (100) NULL,
    [Zalo]          NVARCHAR (100) NULL,
    [Viber]         NVARCHAR (100) NULL,
    [OtherContact]  NVARCHAR (100) NULL,
    [TaxCode]       NVARCHAR (100) NULL,
    [NationalityId] INT            NULL,
    [Email]         VARCHAR (50)   NULL,
    [IsPrioritize]  BIT            CONSTRAINT [DF_CustomerContact_IsPrioritize] DEFAULT ((0)) NOT NULL,
    [Position]      NVARCHAR (50)  NULL,
    [Active]        BIT            NOT NULL,
    [UpdatedDate]   DATETIME2 (7)  NULL,
    [UpdatedBy]     INT            NOT NULL,
    [InsertedDate]  DATETIME2 (7)  NULL,
    [InsertedBy]    INT            NOT NULL,
    [TanentId]      INT            NOT NULL,
    CONSTRAINT [PK_CustomerContact] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CustomerContact_Terminal] FOREIGN KEY ([TerminalId]) REFERENCES [dbo].[Terminal] ([Id]),
    CONSTRAINT [FK_CustomerContact_Vendor] FOREIGN KEY ([VendorId]) REFERENCES [dbo].[Vendor] ([Id])
);

