CREATE TABLE [dbo].[CustomerContract] (
    [Id]              INT             IDENTITY (1, 1) NOT NULL,
    [ContractDate]    DATETIME2 (7)   NULL,
    [EffectiveDate]   DATETIME2 (7)   NULL,
    [ExpriredDate]    DATETIME2 (7)   NULL,
    [CommodityTypeId] INT             NULL,
    [Progress]        DECIMAL (4, 2)  NOT NULL,
    [Volume]          DECIMAL (20, 5) NOT NULL,
    [Weight]          DECIMAL (20, 5) NOT NULL,
    [ContractNo]      VARCHAR (50)    NULL,
    [CurrencyId]      INT             NULL,
    [ExchangeRate]    DECIMAL (20, 5) NULL,
    [BankId]          INT             NULL,
    [Attachments]     NVARCHAR (500)  NULL,
    [Distance]        DECIMAL (20, 5) NOT NULL,
    [CustomerId]      INT             NULL,
    [QuotationId]     INT             NULL,
    [OrderPeriodId]   INT             NULL,
    [EstimatedCost]   DECIMAL (20, 5) NOT NULL,
    [Notes]           NVARCHAR (MAX)  NULL,
    [InsertedDate]    DATETIME2 (7)   NULL,
    [InsertedBy]      INT             NOT NULL,
    [UpdatedDate]     DATETIME2 (7)   NULL,
    [UpdatedBy]       INT             NULL,
    [Active]          BIT             NOT NULL,
    [TanentId]        INT             NOT NULL,
    CONSTRAINT [PK_ContractCustomer] PRIMARY KEY CLUSTERED ([Id] ASC)
);

