CREATE TABLE [dbo].[FamilyAllowances] (
    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
    [UserId]               INT            NOT NULL,
    [AssistantId]          INT            NULL,
    [DoB]                  DATETIME2 (7)  NULL,
    [DoBCertificateNo]     VARCHAR (50)   NULL,
    [NationalityId]        INT            NULL,
    [Address]              NVARCHAR (300) NULL,
    [TaxCode]              VARCHAR (50)   NULL,
    [Ssn]                  VARCHAR (50)   NULL,
    [Relationship]         NVARCHAR (50)  NULL,
    [StartDate]            DATETIME2 (7)  NULL,
    [EndDate]              DATETIME2 (7)  NULL,
    [Attachments]          NVARCHAR (MAX) NULL,
    [FamilyAllowancesDate] DATETIME2 (7)  NULL,
    [Active]               BIT            NOT NULL,
    [InsertedDate]         DATETIME2 (7)  NOT NULL,
    [InsertedBy]           INT            NOT NULL,
    [UpdatedDate]          DATETIME2 (7)  NULL,
    [UpdatedBy]            INT            NULL,
    [TanentId]             INT            NOT NULL,
    CONSTRAINT [PK_FamilyAllowances] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_FamilyAllowances_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([Id])
);

