CREATE TABLE [dbo].[Feature] (
    [Id]           INT            IDENTITY (1, 1) NOT NULL,
    [Name]         NVARCHAR (100) NULL,
    [Label]        NVARCHAR (100) NULL,
    [ParentId]     INT            NULL,
    [Order]        INT            NULL,
    [ClassName]    VARCHAR (50)   NULL,
    [Style]        VARCHAR (50)   NULL,
    [StyleSheet]   VARCHAR (MAX)  NULL,
    [Script]       NVARCHAR (MAX) NULL,
    [Events]       VARCHAR (200)  NULL,
    [Icon]         VARCHAR (50)   NULL,
    [IsDevider]    BIT            NOT NULL,
    [IsGroup]      BIT            NOT NULL,
    [IsMenu]       BIT            CONSTRAINT [DF_Feature_IsMenu] DEFAULT ((0)) NOT NULL,
    [IsPublic]     BIT            CONSTRAINT [DF_Feature_IsMenu1] DEFAULT ((0)) NOT NULL,
    [StartUp]      BIT            NOT NULL,
    [ViewClass]    VARCHAR (150)  NULL,
    [EntityId]     INT            NULL,
    [Description]  NVARCHAR (500) NULL,
    [Active]       BIT            NOT NULL,
    [InsertedDate] DATETIME2 (7)  NOT NULL,
    [InsertedBy]   INT            NOT NULL,
    [UpdatedDate]  DATETIME2 (7)  NULL,
    [UpdatedBy]    INT            NULL,
    [IsSystem]     BIT            DEFAULT ((0)) NOT NULL,
    [TanentId]     INT            NOT NULL,
    CONSTRAINT [PK_Feature] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Feature_Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id]),
    CONSTRAINT [FK_Feature_Parent] FOREIGN KEY ([ParentId]) REFERENCES [dbo].[Feature] ([Id])
);

