CREATE TABLE [dbo].[FuelHistory] (
    [Id]               INT             IDENTITY (1, 1) NOT NULL,
    [Litre]            DECIMAL (20, 5) NOT NULL,
    [Cost]             DECIMAL (20, 5) NOT NULL,
    [PriceBeforeTax]   DECIMAL (20, 5) NOT NULL,
    [Vat]              DECIMAL (4, 2)  NOT NULL,
    [PriceAfterTax]    DECIMAL (20, 5) NOT NULL,
    [CurrencyId]       INT             NULL,
    [TruckId]          INT             NOT NULL,
    [VendorId]         INT             NULL,
    [Pay]              BIT             NOT NULL,
    [Invoices]         NVARCHAR (MAX)  NULL,
    [Active]           BIT             NOT NULL,
    [InsertedDate]     DATETIME2 (7)   NOT NULL,
    [InsertedBy]       INT             NOT NULL,
    [UpdatedDate]      DATETIME2 (7)   NULL,
    [UpdatedBy]        INT             NULL,
    [ExchangeRate]     DECIMAL (20, 5) NOT NULL,
    [OdoMile]          DECIMAL (20, 2) NOT NULL,
    [Odometer]         DECIMAL (20, 2) NOT NULL,
    [PaymentMethodId]  INT             NULL,
    [InvoiceNo]        VARCHAR (250)   NULL,
    [InvoiceDate]      DATETIME2 (7)   CONSTRAINT [DF_FuelHistory_InvoiceDate] DEFAULT (getdate()) NOT NULL,
    [CreditAccId]      INT             NULL,
    [DebitAccId]       INT             NULL,
    [FuelDate]         DATETIME2 (7)   NULL,
    [LastFuelDate]     DATETIME2 (7)   NULL,
    [PaybackPaymentId] INT             NULL,
    [TanentId]         INT             NOT NULL,
    CONSTRAINT [PK_FuelHistory] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_FuelHistory_Truck] FOREIGN KEY ([TruckId]) REFERENCES [dbo].[Truck] ([Id])
);

