CREATE TABLE [dbo].[GridPolicy] (
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [UniqueId]       UNIQUEIDENTIFIER NULL,
    [FeatureId]      INT              NULL,
    [EntityId]       INT              NOT NULL,
    [FieldName]      NVARCHAR (100)   NULL,
    [Order]          INT              NULL,
    [GroupOrder]     INT              NULL,
    [ShortDesc]      NVARCHAR (50)    NULL,
    [Description]    NVARCHAR (100)   NULL,
    [IsPivot]        BIT              CONSTRAINT [DF_GridPolicy_IsPivot] DEFAULT ((0)) NOT NULL,
    [ReferenceId]    INT              NULL,
    [FilterTemplate] VARCHAR (200)    NULL,
    [RefClass]       VARCHAR (50)     NULL,
    [DataSource]     VARCHAR (1000)   NULL,
    [GroupName]      NVARCHAR (50)    NULL,
    [FormatCell]     NVARCHAR (250)   NULL,
    [FormatRow]      NVARCHAR (250)   NULL,
    [PlainText]      NVARCHAR (250)   NULL,
    [Width]          VARCHAR (20)     NULL,
    [MinWidth]       VARCHAR (20)     NULL,
    [MaxWidth]       VARCHAR (20)     NULL,
    [Precision]      INT              NULL,
    [Validation]     NVARCHAR (1000)  NULL,
    [TextAlign]      VARCHAR (10)     NULL,
    [Frozen]         BIT              CONSTRAINT [DF_GridPolicy_Frozen] DEFAULT ((0)) NOT NULL,
    [Hidden]         BIT              NOT NULL,
    [Events]         VARCHAR (50)     NULL,
    [ClassName]      VARCHAR (50)     NULL,
    [Style]          VARCHAR (200)    NULL,
    [ChildStyle]     VARCHAR (200)    NULL,
    [Icon]           VARCHAR (50)     NULL,
    [AdvancedSearch] BIT              NOT NULL,
    [HasFilter]      BIT              NOT NULL,
    [Editable]       BIT              CONSTRAINT [DF_GridPolicy_Editable] DEFAULT ((0)) NOT NULL,
    [Disabled]       BIT              CONSTRAINT [DF_GridPolicy_Disabled] DEFAULT ((0)) NOT NULL,
    [ComponentType]  VARCHAR (50)     NULL,
    [PopulateField]  VARCHAR (100)    NULL,
    [CascadeField]   VARCHAR (50)     NULL,
    [Summary]        NVARCHAR (50)    NULL,
    [SummaryColSpan] INT              NULL,
    [ComponentId]    INT              NULL,
    [DefaultVal]     NVARCHAR (100)   NULL,
    [Active]         BIT              NOT NULL,
    [InsertedDate]   DATETIME2 (7)    NOT NULL,
    [InsertedBy]     INT              NOT NULL,
    [UpdatedDate]    DATETIME2 (7)    NULL,
    [UpdatedBy]      INT              NULL,
    [TanentId]       INT              NOT NULL,
    [RoleId]         INT              NULL,
    CONSTRAINT [PK_GridPolicy] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_GridPolicy_Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id]),
    CONSTRAINT [FK_GridPolicy_Feature] FOREIGN KEY ([FeatureId]) REFERENCES [dbo].[Feature] ([Id]),
    CONSTRAINT [FK_GridPolicy_RefEntity] FOREIGN KEY ([ReferenceId]) REFERENCES [dbo].[Entity] ([Id])
);

