CREATE TABLE [dbo].[Ledger] (
    [Id]            INT             IDENTITY (1, 1) NOT NULL,
    [Debit]         AS              ([OriginDebit]*[ExchangeRate]),
    [Credit]        AS              ([OriginCredit]*[ExchangeRate]),
    [OriginDebit]   DECIMAL (20, 5) NULL,
    [OriginCredit]  DECIMAL (20, 5) NULL,
    [CurrencyId]    INT             NULL,
    [ExchangeRate]  DECIMAL (20, 5) NULL,
    [AccountTypeId] INT             NOT NULL,
    [InvoiceNo]     VARCHAR (50)    NULL,
    [InvoiceDate]   DATETIME2 (7)   NULL,
    [EntityId]      INT             NULL,
    [RecordId]      INT             NULL,
    [FieldId]       INT             NULL,
    [Note]          NVARCHAR (1500) NULL,
    [Lock]          BIT             CONSTRAINT [DF__Ledger__Lock__1F83A428] DEFAULT ((0)) NOT NULL,
    [Active]        BIT             NOT NULL,
    [InsertedDate]  DATETIME2 (7)   NOT NULL,
    [InsertedBy]    INT             NOT NULL,
    [UpdatedDate]   DATETIME2 (7)   NULL,
    [UpdatedBy]     INT             NULL,
    [TanentId]      INT             NOT NULL,
    CONSTRAINT [PK_Ledger] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TrackEntity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id])
);

