CREATE TABLE [dbo].[OrderHistory] (
    [Id]                      INT             IDENTITY (1, 1) NOT NULL,
    [OrderId]                 INT             NULL,
    [Comment]                 NVARCHAR (100)  NULL,
    [ReasonOfChange]          NVARCHAR (200)  NULL,
    [SendCoordinationDate]    DATETIME2 (7)   NULL,
    [IsContainer]             BIT             NOT NULL,
    [CustomerId]              INT             NULL,
    [ContractId]              INT             NULL,
    [ContactFirstName]        NVARCHAR (50)   NULL,
    [ContactLastName]         NVARCHAR (100)  NULL,
    [PhoneNumber]             VARCHAR (50)    NULL,
    [ContactSSN]              VARCHAR (50)    NULL,
    [ContactPassport]         VARCHAR (50)    NULL,
    [ContactAddress]          NVARCHAR (200)  NULL,
    [FromId]                  INT             NULL,
    [ToId]                    INT             NULL,
    [CustomerContactId]       INT             NULL,
    [ContainerTypeId]         INT             NULL,
    [TruckTypeId]             INT             NULL,
    [TotalContainer]          INT             NULL,
    [FreightStateId]          INT             NULL,
    [StatusId]                INT             CONSTRAINT [DF_OrderHistory_StatusId] DEFAULT ((0)) NOT NULL,
    [IsSend]                  BIT             CONSTRAINT [DF_OrderHistory_IsSend] DEFAULT ((0)) NOT NULL,
    [Deadline]                DATETIME2 (7)   NULL,
    [SaleId]                  INT             NOT NULL,
    [AccountableUserId]       INT             NULL,
    [AccountableDepartmentId] INT             NULL,
    [AdvancedPaid]            DECIMAL (20, 5) NOT NULL,
    [Paid]                    BIT             CONSTRAINT [DF_OrderHistory_Paid] DEFAULT ((0)) NOT NULL,
    [Vat]                     DECIMAL (4, 2)  NOT NULL,
    [TotalPriceBeforeTax]     DECIMAL (20, 5) NOT NULL,
    [TotalPriceAfterTax]      DECIMAL (20, 5) NOT NULL,
    [CurrencyId]              INT             NULL,
    [ExchangeRate]            DECIMAL (20, 5) NOT NULL,
    [FixedExchangeRate]       BIT             CONSTRAINT [DF_OrderHistory_FixedExchangeRate] DEFAULT ((0)) NOT NULL,
    [PaidDate]                DATETIME2 (7)   NULL,
    [ActualEndDate]           DATETIME2 (7)   NULL,
    [Note]                    NVARCHAR (2000) NULL,
    [Note1]                   NVARCHAR (2000) NULL,
    [Reported]                BIT             CONSTRAINT [DF_OrderHistory_Reported] DEFAULT ((0)) NOT NULL,
    [TotalSurchargeBeforeTax] DECIMAL (20, 5) CONSTRAINT [DF_OrderHistory_TotalSurchargeBeforeTax] DEFAULT ((0.0)) NOT NULL,
    [TotalSurchargeAfterTax]  DECIMAL (20, 5) CONSTRAINT [DF_OrderHistory_TotalSurchargeAfterTax] DEFAULT ((0.0)) NOT NULL,
    [HaveToReceiveAfterTax]   DECIMAL (20, 5) CONSTRAINT [DF_OrderHistory_HaveToReceiveAfterTax] DEFAULT ((0)) NOT NULL,
    [HaveToReceiveBeforeTax]  DECIMAL (20, 5) CONSTRAINT [DF_OrderHistory_HaveToReceiveBeforeTax] DEFAULT ((0)) NOT NULL,
    [Mbl]                     VARCHAR (50)    NULL,
    [InvoiceNo]               VARCHAR (50)    NULL,
    [InvoiceDate]             DATETIME2 (7)   NULL,
    [Attachments]             NVARCHAR (MAX)  NULL,
    [Active]                  BIT             NOT NULL,
    [InsertedDate]            DATETIME2 (7)   NOT NULL,
    [InsertedBy]              INT             NOT NULL,
    [UpdatedDate]             DATETIME2 (7)   NULL,
    [UpdatedBy]               INT             NULL,
    [TanentId]                INT             NOT NULL,
    CONSTRAINT [PK_OrderHistory] PRIMARY KEY CLUSTERED ([Id] ASC)
);

