CREATE TABLE [dbo].[OrderDetail] (
    [Id]                      INT             IDENTITY (1, 1) NOT NULL,
    [OrderId]                 INT             NOT NULL,
    [IsCoordination]          BIT             NOT NULL,
    [GoodsName]               NVARCHAR (50)   NULL,
    [ReceivedDate]            DATETIME2 (7)   NULL,
    [DeliveryDate]            DATETIME2 (7)   NULL,
    [Deadline]                DATETIME2 (7)   NULL,
    [TransportDuration]       DECIMAL (20, 5) NULL,
    [EmptyDuration]           DECIMAL (20, 5) NULL,
    [FromId]                  INT             NULL,
    [ToId]                    INT             NULL,
    [EmptyContFromId]         INT             NULL,
    [EmptyContToId]           INT             NULL,
    [ContainerTypeId]         INT             NULL,
    [BlockTypeId]             INT             NULL,
    [CommodityTypeName]       NVARCHAR (100)  NULL,
    [TruckTypeId]             INT             NULL,
    [IsContainer]             BIT             CONSTRAINT [DF_OrderDetail_IsContainer] DEFAULT ((0)) NOT NULL,
    [CommodityTypeId]         INT             NULL,
    [VendorId]                INT             NULL,
    [PortSupplierId]          INT             NULL,
    [ParkingTerminalId]       INT             NULL,
    [ShippingLineId]          INT             NULL,
    [TransportDistance]       DECIMAL (20, 5) NOT NULL,
    [EmptyDistance]           DECIMAL (20, 5) NOT NULL,
    [TerminalStartId]         INT             NULL,
    [TotalWeight]             DECIMAL (20, 5) NOT NULL,
    [TotalVolume]             DECIMAL (20, 5) NOT NULL,
    [TotalBox]                INT             NULL,
    [TotalContainer]          INT             NULL,
    [PickupTimeFrom]          VARCHAR (20)    NULL,
    [PickupTimeTo]            VARCHAR (20)    NULL,
    [DeliveryTimeFrom]        VARCHAR (20)    NULL,
    [DeliveryTimeTo]          VARCHAR (20)    NULL,
    [TotalPriceBeforeTax]     DECIMAL (20, 5) NOT NULL,
    [TotalPriceAfterTax]      DECIMAL (20, 5) NOT NULL,
    [TotalSurchargeBeforeTax] DECIMAL (20, 5) NOT NULL,
    [TotalSurchargeAfterTax]  DECIMAL (20, 5) NOT NULL,
    [HaveToReceiveAfterTax]   DECIMAL (20, 5) NOT NULL,
    [HaveToReceiveBeforeTax]  DECIMAL (20, 5) NOT NULL,
    [QuotationId]             INT             NULL,
    [ExchangeRate]            DECIMAL (20, 5) NOT NULL,
    [Vat]                     DECIMAL (20, 5) NOT NULL,
    [CurrencyId]              INT             NULL,
    [ClosingDate]             DATETIME2 (7)   NULL,
    [ResellBeforeTax]         DECIMAL (20, 5) NOT NULL,
    [ResellAfterTax]          DECIMAL (20, 5) NOT NULL,
    [ResellCurrencyId]        INT             NULL,
    [ResellExchangeRate]      DECIMAL (20, 5) NOT NULL,
    [FreightStateId]          INT             NULL,
    [Note]                    NVARCHAR (1000) NULL,
    [Note1]                   NVARCHAR (1000) NULL,
    [BookingNo]               NVARCHAR (50)   NULL,
    [Hbl]                     VARCHAR (50)    NULL,
    [PortOfExportId]          INT             NULL,
    [PortOfExportName]        NVARCHAR (50)   NULL,
    [PortOfImportId]          INT             NULL,
    [PortOfImportName]        NVARCHAR (50)   NULL,
    [ContainerMovingTypeId]   INT             CONSTRAINT [DF_OrderDetail_IsImport] DEFAULT ((0)) NULL,
    [RouteId]                 INT             NULL,
    [Active]                  BIT             NOT NULL,
    [InsertedDate]            DATETIME2 (7)   NOT NULL,
    [InsertedBy]              INT             NOT NULL,
    [UpdatedDate]             DATETIME2 (7)   NULL,
    [UpdatedBy]               INT             NULL,
    [SealNumbersCont]         NVARCHAR (50)   NULL,
    [ContainerNo]             VARCHAR (50)    NULL,
    [TanentId]                INT             NOT NULL,
    CONSTRAINT [PK_OrderDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_OrderDetail_ContainerType] FOREIGN KEY ([ContainerTypeId]) REFERENCES [dbo].[MasterData] ([Id]),
    CONSTRAINT [FK_OrderDetail_Order] FOREIGN KEY ([OrderId]) REFERENCES [dbo].[Order] ([Id]),
    CONSTRAINT [FK_OrderDetail_Quotation] FOREIGN KEY ([QuotationId]) REFERENCES [dbo].[Quotation] ([Id]),
    CONSTRAINT [FK_OrderDetail_Route] FOREIGN KEY ([RouteId]) REFERENCES [dbo].[Route] ([Id]),
    CONSTRAINT [FK_OrderDetail_TruckType] FOREIGN KEY ([TruckTypeId]) REFERENCES [dbo].[MasterData] ([Id]),
    CONSTRAINT [FK_OrderDetail_Vendor] FOREIGN KEY ([VendorId]) REFERENCES [dbo].[Vendor] ([Id])
);

