CREATE TABLE [dbo].[Payable] (
    [Id]              INT             IDENTITY (1, 1) NOT NULL,
    [CostCenterId]    INT             NULL,
    [StateId]         INT             NULL,
    [EntityId]        INT             NULL,
    [SupplierId]      INT             NULL,
    [StatusId]        INT             CONSTRAINT [DF_Payable_StatusId] DEFAULT ((0)) NOT NULL,
    [IsSend]          BIT             CONSTRAINT [DF_Payable_IsSend] DEFAULT ((0)) NOT NULL,
    [FromDate]        DATETIME2 (7)   NULL,
    [ToDate]          DATETIME2 (7)   NULL,
    [OpeningDebit]    DECIMAL (20, 5) CONSTRAINT [DF_Payable_OpeningDebit] DEFAULT ((0)) NOT NULL,
    [ClosingDebit]    DECIMAL (20, 5) CONSTRAINT [DF_Payable_ClosingDebit] DEFAULT ((0)) NOT NULL,
    [HaveToPay]       DECIMAL (20, 5) CONSTRAINT [DF_Payable_HaveToPay] DEFAULT ((0)) NOT NULL,
    [Deadline]        DATETIME2 (7)   NULL,
    [TotalPaid]       DECIMAL (20, 5) CONSTRAINT [DF_Payable_TotalPaid] DEFAULT ((0)) NOT NULL,
    [Clearing]        DECIMAL (20, 5) CONSTRAINT [DF_Payable_Clearing] DEFAULT ((0)) NOT NULL,
    [PriceBeforeTax]  DECIMAL (20, 5) NOT NULL,
    [PriceAfterTax]   DECIMAL (20, 5) NOT NULL,
    [CurrencyId]      INT             NULL,
    [ExchangeRate]    DECIMAL (20, 5) NOT NULL,
    [PaymentMethodId] INT             NULL,
    [Attachment]      NVARCHAR (MAX)  NULL,
    [IsManual]        BIT             NOT NULL,
    [IsPaid]          BIT             NOT NULL,
    [PaidBy]          INT             NULL,
    [Note]            NVARCHAR (MAX)  NULL,
    [PaidDate]        DATETIME2 (7)   NULL,
    [Active]          BIT             NOT NULL,
    [InsertedDate]    DATETIME2 (7)   NOT NULL,
    [InsertedBy]      INT             NOT NULL,
    [UpdatedDate]     DATETIME2 (7)   NULL,
    [UpdatedBy]       INT             NULL,
    [TanentId]        INT             NOT NULL,
    CONSTRAINT [PK_Payable] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Payable_Curr] FOREIGN KEY ([Id]) REFERENCES [dbo].[Payable] ([Id]),
    CONSTRAINT [FK_Payable_Supplier] FOREIGN KEY ([SupplierId]) REFERENCES [dbo].[Vendor] ([Id]),
    CONSTRAINT [FK_Payable_User] FOREIGN KEY ([InsertedBy]) REFERENCES [dbo].[User] ([Id])
);

