CREATE TABLE [dbo].[PayableDetail] (
    [Id]                   INT             IDENTITY (1, 1) NOT NULL,
    [PayableId]            INT             NULL,
    [SupplierId]           INT             NULL,
    [CoordinationDetailId] INT             NULL,
    [TruckId]              INT             NULL,
    [EntityId]             INT             NULL,
    [RecordId]             INT             NULL,
    [PayableType]          NVARCHAR (50)   NOT NULL,
    [CurrencyId]           INT             NULL,
    [ExchangeRate]         DECIMAL (20, 5) NOT NULL,
    [PriceBeforeTax]       DECIMAL (20, 5) NOT NULL,
    [Vat]                  DECIMAL (4, 2)  NOT NULL,
    [PriceAfterTax]        DECIMAL (20, 5) NOT NULL,
    [InvoiceNo]            VARCHAR (100)   NULL,
    [InvoiceDate]          DATETIME2 (7)   NULL,
    [Attachments]          NVARCHAR (MAX)  NULL,
    [Description]          NVARCHAR (200)  NULL,
    [Active]               BIT             NOT NULL,
    [InsertedDate]         DATETIME2 (7)   NOT NULL,
    [InsertedBy]           INT             NOT NULL,
    [UpdatedDate]          DATETIME2 (7)   NULL,
    [UpdatedBy]            INT             NULL,
    [TanentId]             INT             NOT NULL,
    CONSTRAINT [PK_PayableDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PayableDetail_Payable] FOREIGN KEY ([PayableId]) REFERENCES [dbo].[Payable] ([Id])
);

