CREATE TABLE [dbo].[PaybackPayment] (
    [Id]                   INT             IDENTITY (1, 1) NOT NULL,
    [CostCenterId]         INT             NULL,
    [UserId]               INT             NULL,
    [TotalAdvancedPayment] DECIMAL (20, 5) CONSTRAINT [DF_PaybackPayment_AdvancedPayment] DEFAULT ((0)) NOT NULL,
    [TotalReceived]        DECIMAL (20, 5) NOT NULL,
    [TotalPaid]            DECIMAL (20, 5) NOT NULL,
    [Refund]               DECIMAL (20, 5) CONSTRAINT [DF_PaybackPayment_Refund] DEFAULT ((0)) NOT NULL,
    [Debit]                DECIMAL (20, 5) NOT NULL,
    [CurrencyId]           INT             NULL,
    [ExchangeRate]         DECIMAL (20, 5) CONSTRAINT [DF_PaybackPayment_ExchangeRate] DEFAULT ((1)) NOT NULL,
    [FixedExchangeRate]    BIT             CONSTRAINT [DF_PaybackPayment_FixedExchangeRate] DEFAULT ((0)) NOT NULL,
    [SalaryDeduction]      BIT             NOT NULL,
    [PaybackPaymentDate]   DATETIME2 (7)   NULL,
    [StatusId]             INT             CONSTRAINT [DF_PaybackPayment_StatusId] DEFAULT ((2)) NOT NULL,
    [HasPaid]              BIT             NOT NULL,
    [IsSend]               BIT             CONSTRAINT [DF_PaybackPayment_IsSend] DEFAULT ((0)) NOT NULL,
    [Notes]                NVARCHAR (500)  NULL,
    [Active]               BIT             NOT NULL,
    [InsertedDate]         DATETIME2 (7)   NOT NULL,
    [InsertedBy]           INT             NOT NULL,
    [UpdatedDate]          DATETIME2 (7)   NULL,
    [UpdatedBy]            INT             NULL,
    [TanentId]             INT             NOT NULL,
    CONSTRAINT [PK_PaybackPayment] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PaybackPayment_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([Id])
);

