CREATE TABLE [dbo].[PayslipDetail] (
    [Id]                INT             IDENTITY (1, 1) NOT NULL,
    [PayslipId]         INT             NOT NULL,
    [UserId]            INT             NOT NULL,
    [Month]             INT             NOT NULL,
    [Year]              INT             NOT NULL,
    [InsuranceSalary]   DECIMAL (20, 5) NOT NULL,
    [Commission]        DECIMAL (20, 5) NOT NULL,
    [GrossSalary]       DECIMAL (20, 5) NOT NULL,
    [IncomeTax]         DECIMAL (20, 5) NOT NULL,
    [NetSalary]         DECIMAL (20, 5) NOT NULL,
    [Allowance]         DECIMAL (20, 5) NOT NULL,
    [Allowance2]        DECIMAL (20, 5) NOT NULL,
    [Allowance3]        DECIMAL (20, 5) NOT NULL,
    [Allowance4]        DECIMAL (20, 5) NOT NULL,
    [WorkingDay]        INT             NOT NULL,
    [Insurance1]        DECIMAL (20, 5) NOT NULL,
    [Insurance2]        DECIMAL (20, 5) NOT NULL,
    [Insurance3]        DECIMAL (20, 5) NOT NULL,
    [Insurance4]        DECIMAL (20, 5) NOT NULL,
    [AmountPayback]     DECIMAL (20, 5) NOT NULL,
    [AdvancePayment]    DECIMAL (20, 5) NOT NULL,
    [Bonus1]            DECIMAL (20, 5) NOT NULL,
    [Bonus2]            DECIMAL (20, 5) NOT NULL,
    [Bonus3]            DECIMAL (20, 5) NOT NULL,
    [Bonus4]            DECIMAL (20, 5) NOT NULL,
    [CompanyInsurance1] DECIMAL (20, 5) NULL,
    [CompanyInsurance2] DECIMAL (20, 5) NULL,
    [CompanyInsurance3] DECIMAL (20, 5) NULL,
    [CompanyInsurance4] DECIMAL (20, 5) NULL,
    [Active]            BIT             NOT NULL,
    [InsertedDate]      DATETIME2 (7)   NOT NULL,
    [InsertedBy]        INT             NOT NULL,
    [UpdatedDate]       DATETIME2 (7)   NULL,
    [UpdatedBy]         INT             NULL,
    [TanentId]          INT             NOT NULL,
    CONSTRAINT [PK_PayslipDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Payslip_UserDriver] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_PayslipDetail_Payslip] FOREIGN KEY ([PayslipId]) REFERENCES [dbo].[Payslip] ([Id])
);

