CREATE TABLE [dbo].[QuotationSurcharge] (
    [Id]              INT             IDENTITY (1, 1) NOT NULL,
    [QuotationId]     INT             NOT NULL,
    [SurchargeTypeId] INT             NULL,
    [PriceTypeId]     INT             NULL,
    [AutoAdd]         BIT             NOT NULL,
    [Min]             DECIMAL (20, 5) NOT NULL,
    [Max]             DECIMAL (20, 5) NULL,
    [MinSpecVolume]   DECIMAL (20, 5) NULL,
    [MaxSpecVolume]   DECIMAL (20, 5) NULL,
    [MinVolume]       DECIMAL (20, 5) NULL,
    [MaxVolume]       DECIMAL (20, 5) NULL,
    [MinWeight]       DECIMAL (20, 5) NULL,
    [MaxWeight]       DECIMAL (20, 5) NULL,
    [MinDistance]     DECIMAL (20, 5) NULL,
    [MaxDistance]     DECIMAL (20, 5) NULL,
    [MinCont]         INT             NULL,
    [MaxCont]         INT             NULL,
    [FixedPrice]      BIT             NOT NULL,
    [Vat]             DECIMAL (4, 2)  NOT NULL,
    [CurrencyId]      INT             NOT NULL,
    [ExchangeRate]    DECIMAL (20, 5) NOT NULL,
    [UnitPrice]       DECIMAL (20, 5) NOT NULL,
    [Note]            NVARCHAR (500)  NULL,
    [Active]          BIT             NOT NULL,
    [InsertedDate]    DATETIME2 (7)   NOT NULL,
    [InsertedBy]      INT             NOT NULL,
    [UpdatedDate]     DATETIME2 (7)   NULL,
    [UpdatedBy]       INT             NULL,
    [TanentId]        INT             NOT NULL,
    CONSTRAINT [PK_QuotationSurcharge] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QuotationSurcharge_Quotation] FOREIGN KEY ([QuotationId]) REFERENCES [dbo].[Quotation] ([Id])
);

