CREATE TABLE [dbo].[Quotation] (
    [Id]                    INT             IDENTITY (1, 1) NOT NULL,
    [UserId]                INT             NULL,
    [StatusId]              INT             NULL,
    [IsUsed]                BIT             CONSTRAINT [DF_Quotation_IsUsed] DEFAULT ((0)) NOT NULL,
    [IsSend]                BIT             CONSTRAINT [DF_Quotation_IsSend] DEFAULT ((0)) NOT NULL,
    [CustomerId]            INT             NULL,
    [CustomerGroupId]       INT             NULL,
    [ContainerMovingTypeId] INT             CONSTRAINT [DF_Quotation_ContainerMovingTypeId] DEFAULT ((0)) NULL,
    [CommodityTypeId]       INT             NULL,
    [ContainerTypeId]       INT             NULL,
    [TruckTypeId]           INT             NULL,
    [ForGroupOnly]          BIT             CONSTRAINT [DF_Quotation_ForGroupOnly] DEFAULT ((0)) NOT NULL,
    [FromId]                INT             NULL,
    [ToId]                  INT             NULL,
    [IsImport]              BIT             NOT NULL,
    [IsExport]              BIT             NOT NULL,
    [TerminalEmptyContId]   INT             NULL,
    [RouteEmptyContId]      INT             NULL,
    [IsContainer]           BIT             CONSTRAINT [DF_Quotation_IsContainer] DEFAULT ((0)) NOT NULL,
    [VendorId]              INT             NULL,
    [TimeboxId]             INT             NULL,
    [EffectiveDate]         DATETIME2 (7)   NULL,
    [ExpiredDate]           DATETIME2 (7)   NULL,
    [CurrencyId]            INT             NULL,
    [VAT]                   DECIMAL (4, 2)  NOT NULL,
    [ExchangeRate]          DECIMAL (20, 5) NOT NULL,
    [MinPrice]              DECIMAL (20, 5) NULL,
    [Name]                  NVARCHAR (100)  NULL,
    [Active]                BIT             NOT NULL,
    [InsertedDate]          DATETIME2 (7)   NOT NULL,
    [InsertedBy]            INT             NOT NULL,
    [UpdatedDate]           DATETIME2 (7)   NULL,
    [UpdatedBy]             INT             NULL,
    [TanentId]              INT             NOT NULL,
    [RoleId]                INT             NULL,
    [IsPublic]              BIT             NOT NULL,
    CONSTRAINT [PK_Quotation] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Quotation_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Vendor] ([Id]),
    CONSTRAINT [FK_Quotation_TerminalFrom] FOREIGN KEY ([FromId]) REFERENCES [dbo].[MasterData] ([Id]),
    CONSTRAINT [FK_Quotation_TerminalTo] FOREIGN KEY ([ToId]) REFERENCES [dbo].[MasterData] ([Id]),
    CONSTRAINT [FK_Quotation_Timebox] FOREIGN KEY ([TimeboxId]) REFERENCES [dbo].[Timebox] ([Id]),
    CONSTRAINT [FK_Quotation_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_Quotation_Vendor] FOREIGN KEY ([VendorId]) REFERENCES [dbo].[Vendor] ([Id])
);

