CREATE TABLE [dbo].[QuotationDetail] (
    [Id]            INT             IDENTITY (1, 1) NOT NULL,
    [Vat]           DECIMAL (4, 2)  NULL,
    [QuotationId]   INT             NOT NULL,
    [PriceTypeId]   INT             NULL,
    [Min]           DECIMAL (20, 5) NOT NULL,
    [Max]           DECIMAL (20, 5) NULL,
    [FixedPrice]    BIT             CONSTRAINT [DF__Quotation__Fixed__76577163] DEFAULT ((0)) NOT NULL,
    [MinSpecVolume] DECIMAL (20, 5) NULL,
    [MaxSpecVolume] DECIMAL (20, 5) NULL,
    [MinVolume]     DECIMAL (20, 5) NULL,
    [MaxVolume]     DECIMAL (20, 5) NULL,
    [MinWeight]     DECIMAL (20, 5) NULL,
    [MaxWeight]     DECIMAL (20, 5) NULL,
    [MinDistance]   DECIMAL (20, 5) NULL,
    [MaxDistance]   DECIMAL (20, 5) NULL,
    [MinCont]       INT             NULL,
    [MaxCont]       INT             NULL,
    [UnitPrice]     DECIMAL (20, 5) NOT NULL,
    [Active]        BIT             NOT NULL,
    [InsertedDate]  DATETIME2 (7)   NOT NULL,
    [InsertedBy]    INT             NOT NULL,
    [UpdatedDate]   DATETIME2 (7)   NULL,
    [UpdatedBy]     INT             NULL,
    [TanentId]      INT             NOT NULL,
    CONSTRAINT [PK_QuotationDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QuotationDetail_Quotation] FOREIGN KEY ([QuotationId]) REFERENCES [dbo].[Quotation] ([Id]),
    CONSTRAINT [FK_QuotationDetail_QuotationDetail] FOREIGN KEY ([Id]) REFERENCES [dbo].[QuotationDetail] ([Id])
);

