CREATE TABLE [dbo].[Receivable] (
    [Id]                    INT             IDENTITY (1, 1) NOT NULL,
    [CostCenterId]          INT             NULL,
    [CustomerId]            INT             NULL,
    [CurrencyId]            INT             NOT NULL,
    [ExchangeRate]          DECIMAL (20, 5) CONSTRAINT [DF_Receivable_ExchangeRate] DEFAULT ((1)) NOT NULL,
    [FromDate]              DATETIME2 (7)   CONSTRAINT [DF_Receivable_FromDate] DEFAULT (getdate()) NOT NULL,
    [ToDate]                DATETIME2 (7)   CONSTRAINT [DF_Receivable_ToDate] DEFAULT (getdate()) NULL,
    [IsSend]                BIT             CONSTRAINT [DF_Receivable_IsSend] DEFAULT ((0)) NOT NULL,
    [IsManual]              BIT             NOT NULL,
    [StatusId]              INT             CONSTRAINT [DF_Receivable_StatusId] DEFAULT ((0)) NOT NULL,
    [Deadline]              DATETIME2 (7)   NULL,
    [OpeningCredit]         DECIMAL (20, 5) CONSTRAINT [DF_Receivable_OpeningCredit] DEFAULT ((0)) NOT NULL,
    [ClosingCredit]         DECIMAL (20, 5) CONSTRAINT [DF_Receivable_ClosingCredit] DEFAULT ((0)) NOT NULL,
    [HaveToReceive]         DECIMAL (20, 5) CONSTRAINT [DF_Receivable_HaveToReceived] DEFAULT ((0)) NOT NULL,
    [Received]              DECIMAL (20, 5) CONSTRAINT [DF_Receivable_Received] DEFAULT ((0)) NOT NULL,
    [Clearing]              DECIMAL (20, 5) CONSTRAINT [DF_Receivable_Clearing] DEFAULT ((0)) NOT NULL,
    [DomesticOpeningCredit] DECIMAL (20, 5) CONSTRAINT [DF_Receivable_OpeningCredit1] DEFAULT ((0)) NOT NULL,
    [DomesticClosingCredit] DECIMAL (20, 5) CONSTRAINT [DF_Receivable_ClosingCredit1] DEFAULT ((0)) NOT NULL,
    [DomesticReceived]      DECIMAL (20, 5) CONSTRAINT [DF_Receivable_Received1] DEFAULT ((0)) NOT NULL,
    [DomesticClearing]      DECIMAL (20, 5) CONSTRAINT [DF_Receivable_Clearing1] DEFAULT ((0)) NOT NULL,
    [DomesticHaveToReceive] DECIMAL (20, 5) CONSTRAINT [DF_Receivable_PriceAfterTax] DEFAULT ((0)) NOT NULL,
    [ReceivedMethodId]      INT             NULL,
    [DateTypeId]            INT             NULL,
    [DomesticCurrency]      BIT             CONSTRAINT [DF_Receivable_DomesticCurrency] DEFAULT ((0)) NOT NULL,
    [CountFinishedOnly]     BIT             CONSTRAINT [DF_Receivable_CountFinishedOnly] DEFAULT ((0)) NOT NULL,
    [Attachment]            NVARCHAR (MAX)  NULL,
    [Active]                BIT             NOT NULL,
    [InsertedDate]          DATETIME2 (7)   NOT NULL,
    [InsertedBy]            INT             NOT NULL,
    [UpdatedDate]           DATETIME2 (7)   NULL,
    [UpdatedBy]             INT             NULL,
    [TanentId]              INT             NOT NULL,
    CONSTRAINT [PK_Receivable] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Receivable_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Vendor] ([Id]),
    CONSTRAINT [FK_Receivable_User] FOREIGN KEY ([InsertedBy]) REFERENCES [dbo].[User] ([Id])
);

