CREATE TABLE [dbo].[ReceivableDetail] (
    [Id]                   INT             IDENTITY (1, 1) NOT NULL,
    [CoordinationDetailId] INT             NULL,
    [ReceivableId]         INT             NULL,
    [CustomerId]           INT             NULL,
    [EntityId]             INT             NULL,
    [RecordId]             INT             NULL,
    [PriceBeforeTax]       DECIMAL (20, 5) NOT NULL,
    [Vat]                  DECIMAL (4, 2)  CONSTRAINT [DF_ReceivableDetail_Vat] DEFAULT ((0)) NULL,
    [PriceAfterTax]        DECIMAL (20, 5) NOT NULL,
    [CurrencyId]           INT             NOT NULL,
    [ExchangeRate]         DECIMAL (20, 5) CONSTRAINT [DF_ReceivableDetail_ExchangeRate] DEFAULT ((0)) NOT NULL,
    [InvoiceNo]            VARCHAR (50)    NULL,
    [InvoiceDate]          DATETIME2 (7)   NULL,
    [Attachment]           NVARCHAR (MAX)  NULL,
    [FromId]               INT             NULL,
    [ToId]                 INT             NULL,
    [ReceivedDate]         DATETIME2 (7)   NULL,
    [DeliveryDate]         DATETIME2 (7)   NULL,
    [Active]               BIT             NOT NULL,
    [InsertedDate]         DATETIME2 (7)   NOT NULL,
    [InsertedBy]           INT             NOT NULL,
    [UpdatedDate]          DATETIME2 (7)   NULL,
    [UpdatedBy]            INT             NULL,
    [TanentId]             INT             NOT NULL,
    CONSTRAINT [PK_ReceivableDetail_Id] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ReceivableDetail_Receivable] FOREIGN KEY ([ReceivableId]) REFERENCES [dbo].[Receivable] ([Id])
);

