CREATE TABLE [dbo].[RegistrationFee] (
    [Id]            INT             IDENTITY (1, 1) NOT NULL,
    [TruckId]       INT             NULL,
    [FeeTypeId]     INT             NULL,
    [VendorId]      INT             NULL,
    [FeeDate]       DATETIME2 (7)   NULL,
    [EffectiveDate] DATETIME2 (7)   NULL,
    [ExpiredDate]   DATETIME2 (7)   NULL,
    [Amount]        DECIMAL (20, 5) NOT NULL,
    [CurrencyId]    INT             NULL,
    [ExchangeRate]  DECIMAL (20, 5) NOT NULL,
    [InvoiceNo]     NVARCHAR (50)   NULL,
    [InvoiceDate]   DATETIME2 (7)   NULL,
    [InvoiceForm]   NVARCHAR (30)   NULL,
    [Attachments]   NVARCHAR (500)  NULL,
    [CreditAccId]   INT             NULL,
    [DebitAccId]    INT             NULL,
    [Active]        BIT             NOT NULL,
    [InsertedDate]  DATETIME2 (7)   NOT NULL,
    [InsertedBy]    INT             NOT NULL,
    [UpdatedDate]   DATETIME2 (7)   NULL,
    [UpdatedBy]     INT             NULL,
    [TanentId]      INT             NOT NULL,
    CONSTRAINT [PK_RegistrationFee] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_RegistrationFee_Truck] FOREIGN KEY ([TruckId]) REFERENCES [dbo].[Truck] ([Id])
);

