CREATE TABLE [dbo].[SurchargePayable] (
    [Id]                   INT             IDENTITY (1, 1) NOT NULL,
    [UserId]               INT             NULL,
    [OrderDetailId]        INT             NULL,
    [CoordinationDetailId] INT             NULL,
    [EntityId]             INT             NULL,
    [TargetId]             INT             NULL,
    [SurchargeTypeId]      INT             NULL,
    [PriceTypeId]          INT             NULL,
    [IsVat]                BIT             CONSTRAINT [DF_SurchargePayable_IsVat] DEFAULT ((0)) NOT NULL,
    [Vat]                  DECIMAL (4, 2)  NOT NULL,
    [UnitPrice]            DECIMAL (20, 5) NOT NULL,
    [Quantity]             DECIMAL (20, 5) NOT NULL,
    [TotalVolume]          DECIMAL (20, 5) NOT NULL,
    [TotalWeight]          DECIMAL (20, 5) NOT NULL,
    [Distance]             DECIMAL (20, 5) NOT NULL,
    [TotalContainer]       INT             NOT NULL,
    [PriceAfterTax]        DECIMAL (20, 5) NOT NULL,
    [IsSend]               BIT             CONSTRAINT [DF_SurchargePayable_IsSend] DEFAULT ((0)) NOT NULL,
    [StatusId]             INT             NULL,
    [Note]                 NVARCHAR (200)  NULL,
    [CurrencyId]           INT             NULL,
    [ExchangeRate]         DECIMAL (20, 5) NOT NULL,
    [FixedExchangeRate]    BIT             NOT NULL,
    [Attachments]          NVARCHAR (3000) NULL,
    [PriceBeforeTax]       DECIMAL (20, 5) NOT NULL,
    [CollectOnBehalf]      BIT             NOT NULL,
    [IsPayable]            BIT             NOT NULL,
    [SupplierId]           INT             NULL,
    [InvoiceNo]            VARCHAR (100)   NULL,
    [InvoiceDate]          DATETIME2 (7)   NULL,
    [Description]          NVARCHAR (200)  NULL,
    [TruckId]              INT             NULL,
    [PaybackPaymentId]     INT             NULL,
    [PurposeTypeId]        INT             NULL,
    [Active]               BIT             NOT NULL,
    [InsertedDate]         DATETIME2 (7)   NOT NULL,
    [InsertedBy]           INT             NOT NULL,
    [UpdatedDate]          DATETIME2 (7)   NULL,
    [UpdatedBy]            INT             NULL,
    [TanentId]             INT             NOT NULL,
    CONSTRAINT [PK_SurchargePayable] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SurchargePayable_CoordinationDetail] FOREIGN KEY ([CoordinationDetailId]) REFERENCES [dbo].[CoordinationDetail] ([Id]),
    CONSTRAINT [FK_SurchargePayable_OrderDetail] FOREIGN KEY ([OrderDetailId]) REFERENCES [dbo].[OrderDetail] ([Id]),
    CONSTRAINT [FK_SurchargePayable_PaybackPayment] FOREIGN KEY ([PaybackPaymentId]) REFERENCES [dbo].[PaybackPayment] ([Id]),
    CONSTRAINT [FK_SurchargePayable_Supplier] FOREIGN KEY ([SupplierId]) REFERENCES [dbo].[Vendor] ([Id]),
    CONSTRAINT [FK_SurchargePayable_SurchargeType] FOREIGN KEY ([SurchargeTypeId]) REFERENCES [dbo].[SurchargeType] ([Id])
);

