CREATE TABLE [dbo].[Surcharge] (
    [Id]                   INT             IDENTITY (1, 1) NOT NULL,
    [OrderDetailId]        INT             NOT NULL,
    [CoordinationDetailId] INT             NULL,
    [SupplierId]           INT             NULL,
    [PaybackId]            INT             NULL,
    [EntityId]             INT             NULL,
    [TargetId]             INT             NULL,
    [SurchargeTypeId]      INT             NULL,
    [PriceTypeId]          INT             NULL,
    [Vat]                  DECIMAL (4, 2)  NOT NULL,
    [UnitPrice]            DECIMAL (20, 5) NOT NULL,
    [Quantity]             DECIMAL (20, 5) NOT NULL,
    [TotalVolume]          DECIMAL (20, 5) NOT NULL,
    [TotalWeight]          DECIMAL (20, 5) NOT NULL,
    [Distance]             DECIMAL (20, 5) NOT NULL,
    [TotalContainer]       INT             NOT NULL,
    [PriceAfterTax]        DECIMAL (20, 5) NOT NULL,
    [Note]                 NVARCHAR (200)  NULL,
    [CurrencyId]           INT             NULL,
    [ExchangeRate]         DECIMAL (20, 5) NOT NULL,
    [FixedExchangeRate]    BIT             CONSTRAINT [DF_Surcharge_FixExchangeRate] DEFAULT ((0)) NOT NULL,
    [PurposeTypeId]        INT             NULL,
    [Attachments]          NVARCHAR (3000) NULL,
    [PriceBeforeTax]       DECIMAL (20, 5) NOT NULL,
    [CollectOnBehalf]      BIT             CONSTRAINT [DF_Surcharge_AutoAdd1] DEFAULT ((0)) NOT NULL,
    [IsReceivable]         BIT             CONSTRAINT [DF__Surcharge__IsPay__2858E14B] DEFAULT ((0)) NOT NULL,
    [TotalPaid]            DECIMAL (20, 5) NULL,
    [InvoiceNo]            VARCHAR (100)   NULL,
    [InvoiceDate]          DATETIME2 (7)   NULL,
    [Description]          NVARCHAR (200)  NULL,
    [Active]               BIT             NOT NULL,
    [InsertedDate]         DATETIME2 (7)   NOT NULL,
    [InsertedBy]           INT             NOT NULL,
    [UpdatedDate]          DATETIME2 (7)   NULL,
    [UpdatedBy]            INT             NULL,
    [TanentId]             INT             NOT NULL,
    CONSTRAINT [PK_Surcharge] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Surcharge_CoordinationDetail] FOREIGN KEY ([CoordinationDetailId]) REFERENCES [dbo].[CoordinationDetail] ([Id]),
    CONSTRAINT [FK_Surcharge_OrderDetail] FOREIGN KEY ([OrderDetailId]) REFERENCES [dbo].[OrderDetail] ([Id]),
    CONSTRAINT [FK_Surcharge_Payback] FOREIGN KEY ([PaybackId]) REFERENCES [dbo].[PaybackPayment] ([Id]),
    CONSTRAINT [FK_Surcharge_SurchargeType] FOREIGN KEY ([SurchargeTypeId]) REFERENCES [dbo].[SurchargeType] ([Id])
);

