CREATE TABLE [dbo].[TaskNotification] (
    [Id]           INT             IDENTITY (1, 1) NOT NULL,
    [Title]        NVARCHAR (100)  NULL,
    [Description]  NVARCHAR (200)  NULL,
    [EntityId]     INT             NULL,
    [RecordId]     INT             NULL,
    [Deadline]     DATETIME2 (7)   NOT NULL,
    [StatusId]     INT             NULL,
    [Attachment]   NVARCHAR (MAX)  NULL,
    [AssignedId]   INT             NULL,
    [RoleId]       INT             NULL,
    [TimeConsumed] DECIMAL (20, 5) NOT NULL,
    [TimeRemained] DECIMAL (20, 5) NOT NULL,
    [Progress]     DECIMAL (20, 5) NOT NULL,
    [RemindBefore] FLOAT (53)      NULL,
    [Active]       BIT             NOT NULL,
    [InsertedDate] DATETIME2 (7)   NOT NULL,
    [InsertedBy]   INT             NOT NULL,
    [UpdatedDate]  DATETIME2 (7)   NULL,
    [UpdatedBy]    INT             NULL,
    [TanentId]     INT             NOT NULL,
    CONSTRAINT [PK_TaskNotification] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TaskNotification_Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id]),
    CONSTRAINT [FK_TaskNotification_Role] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[Role] ([Id])
);

