CREATE TABLE [dbo].[TruckStopHistory] (
    [Id]                      INT             IDENTITY (1, 1) NOT NULL,
    [TruckId]                 INT             NULL,
    [TrailerId]               INT             NULL,
    [IsSend]                  BIT             NOT NULL,
    [IsContinues]             BIT             NULL,
    [SurchargeTypeId]         INT             NULL,
    [EntityId]                INT             NULL,
    [EstimatedEndDate]        DATETIME2 (7)   NULL,
    [EstimatedQuantity]       DECIMAL (20, 5) NULL,
    [EstimatedPriceBeforeTax] DECIMAL (20, 5) NULL,
    [EstimatedPriceAfterTax]  DECIMAL (20, 5) NULL,
    [UnitPrice]               DECIMAL (20, 5) NOT NULL,
    [Quantity]                DECIMAL (20, 5) NOT NULL,
    [CoordinationDetailId]    INT             NULL,
    [OrderDetailId]           INT             NULL,
    [UserCoordinationId]      INT             NULL,
    [StatusId]                INT             NULL,
    [StopTypeId]              INT             NULL,
    [StartDate]               DATETIME2 (7)   NULL,
    [EndDate]                 DATETIME2 (7)   NULL,
    [PriceAfterTax]           DECIMAL (20, 5) NOT NULL,
    [Vat]                     DECIMAL (20, 5) NOT NULL,
    [PriceBeforeTax]          DECIMAL (20, 5) NOT NULL,
    [Attachments]             NVARCHAR (3000) NULL,
    [Active]                  BIT             NOT NULL,
    [InsertedDate]            DATETIME2 (7)   NOT NULL,
    [InsertedBy]              INT             NOT NULL,
    [UpdatedDate]             DATETIME2 (7)   NULL,
    [UpdatedBy]               INT             NULL,
    [TanentId]                INT             NOT NULL,
    CONSTRAINT [PK_TruckStopHistory] PRIMARY KEY CLUSTERED ([Id] ASC)
);

