CREATE TABLE [dbo].[Truck] (
    [Id]                      INT             IDENTITY (1, 1) NOT NULL,
    [TruckPlate]              VARCHAR (50)    NULL,
    [BranchId]                INT             NULL,
    [BoxTypeId]               INT             NULL,
    [TrailerId]               INT             NULL,
    [Model]                   NVARCHAR (50)   NULL,
    [Year]                    DECIMAL (4)     NOT NULL,
    [Color]                   NVARCHAR (50)   NULL,
    [Vin]                     VARCHAR (50)    NULL,
    [TruckTypeId]             INT             NULL,
    [FuelTypeId]              INT             NULL,
    [KmPerLit]                FLOAT (53)      NULL,
    [PlateRenewal]            VARCHAR (50)    NULL,
    [DepartmentId]            INT             NULL,
    [Note]                    NVARCHAR (1500) NULL,
    [Image]                   VARCHAR (1500)  NULL,
    [IsInternal]              BIT             CONSTRAINT [DF_Truck_Internal] DEFAULT ((0)) NOT NULL,
    [InUse]                   BIT             NOT NULL,
    [MaxCBM]                  DECIMAL (20, 5) NOT NULL,
    [MaxWeight]               DECIMAL (20, 5) NOT NULL,
    [VendorId]                INT             NULL,
    [BankId]                  INT             NULL,
    [Long]                    FLOAT (53)      NULL,
    [Lat]                     FLOAT (53)      NULL,
    [CargoWidth]              DECIMAL (20, 5) NOT NULL,
    [CargoLength]             DECIMAL (20, 5) NOT NULL,
    [CargoHeight]             DECIMAL (20, 5) CONSTRAINT [DF_Truck_CargoHeight] DEFAULT ((0)) NULL,
    [FreightStateId]          INT             NULL,
    [DriverId]                INT             NULL,
    [Driver2Id]               INT             NULL,
    [Driver3Id]               INT             NULL,
    [MonthlyPaidAmount]       DECIMAL (20, 5) NOT NULL,
    [TotalPrice]              DECIMAL (20, 5) CONSTRAINT [DF_Truck_TotalPrice] DEFAULT ((0)) NOT NULL,
    [CurrencyId]              INT             NULL,
    [BoughtDate]              DATETIME2 (7)   NULL,
    [ActiveDate]              DATETIME2 (7)   NOT NULL,
    [ExpiredDate]             DATETIME2 (7)   NULL,
    [MaintenanceStart]        DATETIME2 (7)   NULL,
    [MaintenanceEnd]          DATETIME2 (7)   NULL,
    [NextMaintenanceDate]     DATETIME2 (7)   NULL,
    [MaintenancePeriod]       TIME (7)        NULL,
    [OdoMileExpiry]           DECIMAL (20, 5) NOT NULL,
    [OdoKmExpiry]             DECIMAL (20, 5) NOT NULL,
    [InitOdoMile]             DECIMAL (20, 5) NOT NULL,
    [InitOdoKm]               DECIMAL (20, 5) NOT NULL,
    [CurrentOdo]              DECIMAL (20, 5) NOT NULL,
    [OdoUpdate]               DECIMAL (20, 5) NULL,
    [OdoUpdateDate]           DATETIME2 (7)   NULL,
    [ExchangeRate]            DECIMAL (20, 5) NOT NULL,
    [TotalPaid]               DECIMAL (20, 5) NOT NULL,
    [AdvancePaid]             DECIMAL (20, 5) NOT NULL,
    [CreditAccId]             INT             NULL,
    [DebitAccId]              INT             NULL,
    [DepreciationCreditAccId] INT             NULL,
    [DepreciationDebitAccId]  INT             NULL,
    [IsRent]                  BIT             CONSTRAINT [DF__Truck__IsRent__7FE0DB9D] DEFAULT ((0)) NOT NULL,
    [RentCreditAccId]         INT             NULL,
    [RentDebitAccId]          INT             NULL,
    [DepreciationCoefficient] DECIMAL (4, 2)  CONSTRAINT [DF__Truck__Coefficie__1F997E18] DEFAULT ((1)) NOT NULL,
    [DepreciationMethodId]    INT             NULL,
    [Anchored]                BIT             NOT NULL,
    [Active]                  BIT             NOT NULL,
    [InsertedDate]            DATETIME2 (7)   NOT NULL,
    [InsertedBy]              INT             NOT NULL,
    [UpdatedDate]             DATETIME2 (7)   NULL,
    [UpdatedBy]               INT             NULL,
    [TanentId]                INT             NOT NULL,
    [RoleId]                  INT             NULL,
    CONSTRAINT [PK_Truck] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Truck_Driver] FOREIGN KEY ([DriverId]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_Truck_TruckType] FOREIGN KEY ([TruckTypeId]) REFERENCES [dbo].[MasterData] ([Id]),
    CONSTRAINT [FK_Truck_Vendor] FOREIGN KEY ([VendorId]) REFERENCES [dbo].[Vendor] ([Id])
);

