CREATE TABLE [dbo].[TruckMaintenance] (
    [Id]                 INT             IDENTITY (1, 1) NOT NULL,
    [PaybackPaymentId]   INT             NULL,
    [TruckId]            INT             NULL,
    [StartDate]          DATETIME2 (7)   NULL,
    [MaintenaneDate]     DATETIME2 (7)   NULL,
    [EndDate]            DATETIME2 (7)   NULL,
    [AdvancedPaid]       DECIMAL (20, 5) NOT NULL,
    [Paid]               BIT             NOT NULL,
    [PriceBeforeTax]     DECIMAL (20, 5) NOT NULL,
    [Vat]                DECIMAL (4, 2)  NOT NULL,
    [PriceAfterTax]      DECIMAL (20, 5) NOT NULL,
    [CurrencyId]         INT             NULL,
    [AccountableUserId]  INT             NULL,
    [PaymentMethodId]    INT             NULL,
    [ExchangeRate]       DECIMAL (20, 5) NOT NULL,
    [CurrentOdo]         DECIMAL (20, 5) NOT NULL,
    [AlteredCreditAccId] INT             NULL,
    [AlteredDebitAccId]  INT             NULL,
    [NewDebitAccId]      INT             NULL,
    [NewCreditAccId]     INT             NULL,
    [TotalCreditAccId]   INT             NULL,
    [TotalDebitAccId]    INT             NULL,
    [ReduceCreditAccId]  INT             NULL,
    [ReduceDebitAccId]   INT             NULL,
    [Attachments]        NVARCHAR (MAX)  NULL,
    [InvoiceNo]          NVARCHAR (30)   NULL,
    [InvoiceForm]        NVARCHAR (30)   NULL,
    [InvoiceDate]        DATETIME2 (7)   NOT NULL,
    [Active]             BIT             NOT NULL,
    [InsertedDate]       DATETIME2 (7)   NOT NULL,
    [InsertedBy]         INT             NOT NULL,
    [UpdatedDate]        DATETIME2 (7)   NULL,
    [UpdatedBy]          INT             NULL,
    [TanentId]           INT             NOT NULL,
    CONSTRAINT [PK_TruckMaintenance] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TruckMaintenance_Truck] FOREIGN KEY ([TruckId]) REFERENCES [dbo].[Truck] ([Id])
);

