CREATE TABLE [dbo].[User] (
    [Id]               INT             IDENTITY (1, 1) NOT NULL,
    [VendorId]         INT             NOT NULL,
    [FirstName]        NVARCHAR (50)   NULL,
    [LastName]         NVARCHAR (100)  NULL,
    [MiddleName]       NVARCHAR (100)  NULL,
    [FullName]         AS              (([FirstName]+' ')+[LastName]),
    [IsInternal]       BIT             CONSTRAINT [DF_User_IsInternal] DEFAULT ((0)) NOT NULL,
    [DoB]              DATETIME2 (7)   NULL,
    [Ssn]              VARCHAR (50)    NULL,
    [Passport]         VARCHAR (50)    NULL,
    [Address]          NVARCHAR (200)  NULL,
    [Address2]         NVARCHAR (200)  NULL,
    [PhoneNumber]      VARCHAR (50)    NULL,
    [PhoneNumber2]     VARCHAR (50)    NULL,
    [NationalityId]    INT             NULL,
    [ContractId]       INT             NULL,
    [BankId]           INT             NULL,
    [BankBranchId]     INT             NULL,
    [BankAccountNo]    NVARCHAR (50)   NULL,
    [BankAccountName]  NVARCHAR (50)   NULL,
    [DepartmentId]     INT             NULL,
    [Avatar]           NVARCHAR (1000) NULL,
    [SupervisorId]     INT             NULL,
    [Password]         NVARCHAR (100)  NULL,
    [UserName]         VARCHAR (50)    NULL,
    [Salt]             VARCHAR (50)    NULL,
    [LoginFailedCount] INT             NULL,
    [LastLogin]        DATETIME2 (7)   NULL,
    [LastFailedLogin]  DATETIME2 (7)   NULL,
    [Email]            VARCHAR (50)    NULL,
    [GenderId]         INT             NOT NULL,
    [Recover]          VARCHAR (200)   NULL,
    [Reported]         BIT             CONSTRAINT [DF__User__Reported__02BD4848] DEFAULT ((0)) NOT NULL,
    [Active]           BIT             NOT NULL,
    [InsertedDate]     DATETIME2 (7)   NOT NULL,
    [InsertedBy]       INT             NOT NULL,
    [UpdatedDate]      DATETIME2 (7)   NULL,
    [UpdatedBy]        INT             NULL,
    [TanentId]         INT             NOT NULL,
    CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_User_User_SupervisorId] FOREIGN KEY ([SupervisorId]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_User_Vendor] FOREIGN KEY ([VendorId]) REFERENCES [dbo].[Vendor] ([Id])
);

