CREATE TABLE [dbo].[Vendor] (
    [Id]                    INT             IDENTITY (1, 1) NOT NULL,
    [VendorTypeId]          INT             NULL,
    [Description]           NVARCHAR (2000) NULL,
    [Avatar]                NVARCHAR (1000) NULL,
    [CustomerGroupId]       INT             NULL,
    [SaleId]                INT             NOT NULL,
    [UserId]                INT             NULL,
    [CustomerStateId]       INT             NULL,
    [LastContactDate]       DATETIME2 (7)   NULL,
    [IsSelf]                BIT             NOT NULL,
    [IsInternal]            BIT             NOT NULL,
    [PhoneNumber]           VARCHAR (50)    NULL,
    [PhoneNumber2]          VARCHAR (50)    NULL,
    [Address]               NVARCHAR (200)  NULL,
    [Address2]              NVARCHAR (200)  NULL,
    [Note]                  NVARCHAR (200)  NULL,
    [Email]                 NVARCHAR (100)  NULL,
    [Fax]                   VARCHAR (50)    NULL,
    [Skype]                 NVARCHAR (100)  NULL,
    [Zalo]                  NVARCHAR (100)  NULL,
    [Viber]                 NVARCHAR (100)  NULL,
    [OtherContact]          NVARCHAR (100)  NULL,
    [TaxCode]               VARCHAR (50)    NULL,
    [CompanyLocalShortName] NVARCHAR (50)   NULL,
    [CompanyInterShortName] NVARCHAR (50)   NULL,
    [CompanyLocalFullName]  NVARCHAR (250)  NULL,
    [CompanyInterFullName]  NVARCHAR (250)  NULL,
    [CompanyLocalAddress]   NVARCHAR (250)  NULL,
    [CompanyInterAddress]   NVARCHAR (250)  NULL,
    [Active]                BIT             NOT NULL,
    [InsertedDate]          DATETIME2 (7)   NOT NULL,
    [InsertedBy]            INT             NOT NULL,
    [UpdatedDate]           DATETIME2 (7)   NULL,
    [UpdatedBy]             INT             NULL,
    [TanentId]              INT             NOT NULL,
    [IsTanent]              BIT             NOT NULL,
    [RoleId]                INT             NULL,
    CONSTRAINT [PK_Vendor] PRIMARY KEY CLUSTERED ([Id] ASC)
);

