CREATE TABLE [dbo].[WorkingDayDetail] (
    [Id]                     INT            IDENTITY (1, 1) NOT NULL,
    [PayslipId]              INT            NOT NULL,
    [UserId]                 INT            NOT NULL,
    [StatusId]               INT            CONSTRAINT [DF_WorkingDayDetail_StatusId] DEFAULT ((0)) NOT NULL,
    [ContractId]             INT            NOT NULL,
    [IsSend]                 BIT            CONSTRAINT [DF_WorkingDayDetail_IsSend] DEFAULT ((0)) NOT NULL,
    [Day1]                   INT            NULL,
    [Day2]                   INT            NULL,
    [Day3]                   INT            NULL,
    [Day4]                   INT            NULL,
    [Day5]                   INT            NULL,
    [Day6]                   INT            NULL,
    [Day7]                   INT            NULL,
    [Day8]                   INT            NULL,
    [Day9]                   INT            NULL,
    [Day10]                  INT            NULL,
    [Day11]                  INT            NULL,
    [Day12]                  INT            NULL,
    [Day13]                  INT            NULL,
    [Day14]                  INT            NULL,
    [Day15]                  INT            NULL,
    [Day16]                  INT            NULL,
    [Day17]                  INT            NULL,
    [Day18]                  INT            NULL,
    [Day19]                  INT            NULL,
    [Day20]                  INT            NULL,
    [Day21]                  INT            NULL,
    [Day22]                  INT            NULL,
    [Day23]                  INT            NULL,
    [Day24]                  INT            NULL,
    [Day25]                  INT            NULL,
    [Day26]                  INT            NULL,
    [Day27]                  INT            NULL,
    [Day28]                  INT            NULL,
    [Day29]                  INT            NULL,
    [Day30]                  INT            NULL,
    [Day31]                  INT            NULL,
    [OTDay1]                 DECIMAL (3, 1) NULL,
    [OTDay2]                 DECIMAL (3, 1) NULL,
    [OTDay3]                 DECIMAL (3, 1) NULL,
    [OTDay4]                 DECIMAL (3, 1) NULL,
    [OTDay5]                 DECIMAL (3, 1) NULL,
    [OTDay6]                 DECIMAL (3, 1) NULL,
    [OTDay7]                 DECIMAL (3, 1) NULL,
    [OTDay8]                 DECIMAL (3, 1) NULL,
    [OTDay9]                 DECIMAL (3, 1) NULL,
    [OTDay10]                DECIMAL (3, 1) NULL,
    [OTDay11]                DECIMAL (3, 1) NULL,
    [OTDay12]                DECIMAL (3, 1) NULL,
    [OTDay13]                DECIMAL (3, 1) NULL,
    [OTDay14]                DECIMAL (3, 1) NULL,
    [OTDay15]                DECIMAL (3, 1) NULL,
    [OTDay16]                DECIMAL (3, 1) NULL,
    [OTDay17]                DECIMAL (3, 1) NULL,
    [OTDay18]                DECIMAL (3, 1) NULL,
    [OTDay19]                DECIMAL (3, 1) NULL,
    [OTDay20]                DECIMAL (3, 1) NULL,
    [OTDay21]                DECIMAL (3, 1) NULL,
    [OTDay22]                DECIMAL (3, 1) NULL,
    [OTDay23]                DECIMAL (3, 1) NULL,
    [OTDay24]                DECIMAL (3, 1) NULL,
    [OTDay25]                DECIMAL (3, 1) NULL,
    [OTDay26]                DECIMAL (3, 1) NULL,
    [OTDay27]                DECIMAL (3, 1) NULL,
    [OTDay28]                DECIMAL (3, 1) NULL,
    [OTDay29]                DECIMAL (3, 1) NULL,
    [OTDay30]                DECIMAL (3, 1) NULL,
    [OTDay31]                DECIMAL (3, 1) NULL,
    [NightOT1]               DECIMAL (3, 1) NULL,
    [NightOT2]               DECIMAL (3, 1) NULL,
    [NightOT3]               DECIMAL (3, 1) NULL,
    [NightOT4]               DECIMAL (3, 1) NULL,
    [NightOT5]               DECIMAL (3, 1) NULL,
    [NightOT6]               DECIMAL (3, 1) NULL,
    [NightOT7]               DECIMAL (3, 1) NULL,
    [NightOT8]               DECIMAL (3, 1) NULL,
    [NightOT9]               DECIMAL (3, 1) NULL,
    [NightOT10]              DECIMAL (3, 1) NULL,
    [NightOT11]              DECIMAL (3, 1) NULL,
    [NightOT12]              DECIMAL (3, 1) NULL,
    [NightOT13]              DECIMAL (3, 1) NULL,
    [NightOT14]              DECIMAL (3, 1) NULL,
    [NightOT15]              DECIMAL (3, 1) NULL,
    [NightOT16]              DECIMAL (3, 1) NULL,
    [NightOT17]              DECIMAL (3, 1) NULL,
    [NightOT18]              DECIMAL (3, 1) NULL,
    [NightOT19]              DECIMAL (3, 1) NULL,
    [NightOT20]              DECIMAL (3, 1) NULL,
    [NightOT21]              DECIMAL (3, 1) NULL,
    [NightOT22]              DECIMAL (3, 1) NULL,
    [NightOT23]              DECIMAL (3, 1) NULL,
    [NightOT24]              DECIMAL (3, 1) NULL,
    [NightOT25]              DECIMAL (3, 1) NULL,
    [NightOT26]              DECIMAL (3, 1) NULL,
    [NightOT27]              DECIMAL (3, 1) NULL,
    [NightOT28]              DECIMAL (3, 1) NULL,
    [NightOT29]              DECIMAL (3, 1) NULL,
    [NightOT30]              DECIMAL (3, 1) NULL,
    [NightOT31]              DECIMAL (3, 1) NULL,
    [TotalWorkingDay]        DECIMAL (3, 1) CONSTRAINT [DF_WorkingDayDetail_TotalWorkingDay] DEFAULT ((0)) NOT NULL,
    [TotalUnpaidLeave]       DECIMAL (3, 1) CONSTRAINT [DF_WorkingDayDetail_TotalUnpaidLeave] DEFAULT ((0)) NOT NULL,
    [TotalAnnualLeave]       DECIMAL (3, 1) CONSTRAINT [DF_WorkingDayDetail_TotalAnnualLeave] DEFAULT ((0)) NOT NULL,
    [TotalHolidayLeave]      DECIMAL (3, 1) CONSTRAINT [DF_WorkingDayDetail_TotalHolidayLeave] DEFAULT ((0)) NOT NULL,
    [TotalMaternityLeave]    DECIMAL (3, 1) CONSTRAINT [DF_WorkingDayDetail_TotalMaternityLeave] DEFAULT ((0)) NOT NULL,
    [TotalSickLeave]         DECIMAL (3, 1) CONSTRAINT [DF_WorkingDayDetail_TotalSickLeave] DEFAULT ((0)) NOT NULL,
    [TotalChildrenSickLeave] DECIMAL (3, 1) CONSTRAINT [DF_WorkingDayDetail_TotalChildrenSickLeave] DEFAULT ((0)) NOT NULL,
    [TotalAccidentLeave]     DECIMAL (3, 1) CONSTRAINT [DF_WorkingDayDetail_TotalAccidentLeave] DEFAULT ((0)) NOT NULL,
    [TotalMarriageLeave]     DECIMAL (3, 1) CONSTRAINT [DF_WorkingDayDetail_TotalMarriageLeave] DEFAULT ((0)) NOT NULL,
    [TotalRelativeLeave]     DECIMAL (3, 1) CONSTRAINT [DF_WorkingDayDetail_TotalRelativeLeave] DEFAULT ((0)) NOT NULL,
    [UnpaidLeave]            DECIMAL (3, 1) NOT NULL,
    [AnnualLeave]            DECIMAL (3, 1) NOT NULL,
    [HolidayLeave]           DECIMAL (3, 1) NOT NULL,
    [MaternityLeave]         DECIMAL (3, 1) NOT NULL,
    [SickLeave]              DECIMAL (3, 1) NOT NULL,
    [ChildrenSickLeave]      DECIMAL (3, 1) NOT NULL,
    [AccidentLeave]          DECIMAL (3, 1) NOT NULL,
    [MarriageLeave]          DECIMAL (3, 1) NOT NULL,
    [RelativeLeave]          DECIMAL (3, 1) NOT NULL,
    [Active]                 BIT            NOT NULL,
    [InsertedDate]           DATETIME2 (7)  NOT NULL,
    [InsertedBy]             INT            NOT NULL,
    [UpdatedDate]            DATETIME2 (7)  NULL,
    [UpdatedBy]              INT            NULL,
    [TanentId]               INT            NOT NULL,
    CONSTRAINT [PK_WorkingDayDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_WorkingDayDetail_Payslip] FOREIGN KEY ([PayslipId]) REFERENCES [dbo].[Payslip] ([Id]),
    CONSTRAINT [FK_WorkingDayDetail_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([Id])
);

