namespace Core.Models
{
    public partial class Component
    {
        public string Id { get; set; }
        public string FieldName { get; set; }
        public int? Order { get; set; }
        public string ComponentType { get; set; }
        public string ComponentGroupId { get; set; }
        public string FormatData { get; set; }
        public string PlainText { get; set; }
        public int? Column { get; set; }
        public int? RowSpan { get; set; }
        public int? Offset { get; set; }
        public int? Row { get; set; }
        public bool CanSearch { get; set; }
        public bool CanCache { get; set; }
        public int? Precision { get; set; }
        public string GroupBy { get; set; }
        public string GroupFormat { get; set; }
        public string Label { get; set; }
        public bool ShowLabel { get; set; }
        public string Icon { get; set; }
        public string ClassName { get; set; }
        public string Style { get; set; }
        public string ChildStyle { get; set; }
        public string HotKey { get; set; }
        public string RefClass { get; set; }
        public string Events { get; set; }
        public bool Disabled { get; set; }
        public bool Visibility { get; set; }
        public string Validation { get; set; }
        public bool Focus { get; set; }
        public string Width { get; set; }
        public string PopulateField { get; set; }
        public string GroupEvent { get; set; }
        public int? XsCol { get; set; }
        public int? SmCol { get; set; }
        public int? LgCol { get; set; }
        public int? XlCol { get; set; }
        public int? XxlCol { get; set; }
        public string DefaultVal { get; set; }
        public string DateTimeField { get; set; }
        public bool Active { get; set; }
        public DateTime? InsertedDate { get; set; }
        public string InsertedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public bool CanAdd { get; set; }
        public bool IsPrivate { get; set; }
        public int? MonthCount { get; set; }
        public string Query { get; set; }
        public bool IsRealtime { get; set; }
        public string RefName { get; set; }
        public bool TopEmpty { get; set; }
        public bool IsCollapsible { get; set; }
        public string Template { get; set; }
        public string PreQuery { get; set; }
        public string DisabledExp { get; set; }
        public bool FocusSearch { get; set; }
        public bool IsSumary { get; set; }
        public string FormatSumaryField { get; set; }
        public string OrderBySumary { get; set; }
        public bool ShowHotKey { get; set; }
        public int? DefaultAddStart { get; set; }
        public int? DefaultAddEnd { get; set; }
        public bool UpperCase { get; set; }
        public string Migration { get; set; }
        public string ListClass { get; set; }
        public string ExcelFieldName { get; set; }
        public bool LiteGrid { get; set; }
        public bool ShowDatetimeField { get; set; }
        public bool ShowNull { get; set; }
        public bool AddDate { get; set; }
        public bool FilterEq { get; set; }
        public int? HeaderHeight { get; set; }
        public int? BodyItemHeight { get; set; }
        public int? FooterHeight { get; set; }
        public int? ScrollHeight { get; set; }
        public string ScriptValidation { get; set; }
        public bool FilterLocal { get; set; }
        public bool HideGrid { get; set; }
        public string GroupReferenceId { get; set; }
        public string GroupReferenceName { get; set; }
        public string GroupName { get; set; }
        public string ShortDesc { get; set; }
        public string Description { get; set; }
        public string FeatureId { get; set; }
        public string ComponentId { get; set; }
        public string TextAlign { get; set; }
        public bool HasFilter { get; set; }
        public bool Frozen { get; set; }
        public string FilterTemplate { get; set; }
        public bool Editable { get; set; }
        public string FormatExcell { get; set; }
        public string DatabaseName { get; set; }
        public string Summary { get; set; }
        public int? SummaryColSpan { get; set; }
        public bool BasicSearch { get; set; }
        public string ShowExp { get; set; }
        public string MinWidth { get; set; }
        public string MaxWidth { get; set; }
        public string TenantCode { get; set; }
        public string OrderBy { get; set; }
        public string ParentId { get; set; }
        public string Lang { get; set; }
        public string Name { get; set; }
        public bool IsTab { get; set; }
        public string TabGroup { get; set; }
        public bool IsVertialTab { get; set; }
        public bool Responsive { get; set; }
        public int? OuterColumn { get; set; }
        public int? XsOuterColumn { get; set; }
        public int? SmOuterColumn { get; set; }
        public int? LgOuterColumn { get; set; }
        public int? XlOuterColumn { get; set; }
        public int? XxlOuterColumn { get; set; }
        public int? BadgeMonth { get; set; }
        public bool IsDropDown { get; set; }
        public string Html { get; set; }
        public string Css { get; set; }
        public string Javascript { get; set; }
        public string CreatedBy { get; set; }
        public string EntityId { get; set; }
        public bool DisplayBadge { get; set; }
        public bool IsMultiple { get; set; }
        public string AddRowExp { get; set; }
        public string GroupTypeId { get; set; }
        public string EntityName { get; set; }
        public string ComponentDefaultValueId { get; set; }
        public bool VirtualScroll { get; set; }
        public List<Component> Children { get; set; }
        public List<Component> Components { get; set; }
        public Component Parent { get; set; }
    }
}