-- PostgreSQL Schema for CRM Database
-- Converted from SQL Server (T-SQL)

-- Create database (run separately if needed)
-- CREATE DATABASE crm;

-- Dictionary table
CREATE TABLE "Dictionary" (
    "Id" varchar(50) NOT NULL,
    "LangCode" varchar(250) NULL,
    "Key" varchar(250) NULL,
    "Value" varchar(250) NULL,
    "Active" boolean NOT NULL,
    "InsertedBy" varchar(50) NULL,
    "InsertedDate" timestamptz NULL,
    "UpdatedBy" varchar(50) NULL,
    "UpdatedDate" timestamptz NULL,
    PRIMARY KEY ("Id")
);

-- FileUpload table
CREATE TABLE "FileUpload" (
    "Id" varchar(50) NOT NULL,
    "EntityName" varchar(250) NULL,
    "RecordId" varchar(50) NULL,
    "SectionId" varchar(50) NULL,
    "FieldName" varchar(100) NULL,
    "FileName" varchar(400) NULL,
    "FilePath" varchar(400) NULL,
    "Active" boolean NOT NULL,
    "InsertedDate" timestamptz NULL,
    "InsertedBy" varchar(50) NULL,
    "UpdatedDate" timestamptz NULL,
    "UpdatedBy" varchar(50) NULL,
    PRIMARY KEY ("Id")
);

-- History table
CREATE TABLE "History" (
    "Id" varchar(50) NOT NULL,
    "TextContent" text NULL,
    "Value" text NULL,
    "OldValue" text NULL,
    "ComponentId" varchar(50) NULL,
    "RecordId" varchar(50) NULL,
    "TableName" varchar(250) NULL,
    "Active" boolean NOT NULL,
    "InsertedDate" timestamptz NULL,
    "InsertedBy" varchar(50) NULL,
    "UpdatedDate" timestamptz NULL,
    "UpdatedBy" varchar(50) NULL,
    "created_by" varchar(255) NULL,
    PRIMARY KEY ("Id")
);

-- MasterData table
CREATE TABLE "MasterData" (
    "Id" varchar(50) NOT NULL,
    "Code" varchar(500) NULL,
    "Name" varchar(500) NULL,
    "Description" varchar(500) NULL,
    "ParentId" varchar(50) NULL,
    "Path" varchar(1000) NULL,
    "IsLocal" boolean NOT NULL DEFAULT false,
    "IsContainer" boolean NOT NULL DEFAULT false,
    "IsCBM" boolean NOT NULL DEFAULT false,
    "IsKGS" boolean NOT NULL DEFAULT false,
    "IsGW" boolean NOT NULL DEFAULT false,
    "Active" boolean NOT NULL DEFAULT false,
    "InsertedDate" timestamptz NULL,
    "InsertedBy" varchar(50) NULL,
    "UpdatedDate" timestamptz NULL,
    "UpdatedBy" varchar(50) NULL,
    "Enum" int NULL,
    "GroupEnum" int NULL,
    "CodeMn" varchar(150) NULL,
    PRIMARY KEY ("Id")
);

-- Partner table
CREATE TABLE "Partner" (
    "Id" varchar(50) NOT NULL,
    "ServiceId" int NULL,
    "TypeId" int NULL,
    "Name" varchar(500) NULL,
    "FullName" varchar(500) NULL,
    "DebitName" varchar(500) NULL,
    "Address" varchar(500) NULL,
    "PhoneNumber" varchar(50) NULL,
    "Mail" varchar(200) NULL,
    "Active" boolean NOT NULL,
    "InsertedDate" timestamptz NULL,
    "InsertedBy" varchar(50) NULL,
    "UpdatedDate" timestamptz NULL,
    "UpdatedBy" varchar(50) NULL,
    "Code" varchar(250) NULL,
    "TaxCode" varchar(250) NULL,
    "GroupId" varchar(50) NULL,
    "GenderId" varchar(50) NULL,
    "IssuedDate" timestamptz NULL,
    "Note" varchar(500) NULL,
    "GenderContactId" varchar(50) NULL,
    "ContactName" varchar(500) NULL,
    "ContactEmail" varchar(255) NULL,
    "ContactPhoneNumber" varchar(50) NULL,
    "DebitDay" int NULL,
    "DebitAmount" numeric(19,4) NULL,
    "CreditLimit" numeric(19,4) NULL,
    "DebitAccountId" varchar(50) NULL,
    "IsPublic" boolean NOT NULL,
    "Web" varchar(255) NULL,
    "SeqKey" int NULL,
    "SaleId" varchar(50) NULL,
    "Attachment" varchar(500) NULL,
    "Email" varchar(255) NULL,
    "SourseId" varchar(50) NULL,
    "RaitingId" varchar(50) NULL,
    "Dob" timestamptz NULL,
    "PicId" varchar(50) NULL,
    "CustomerTypeId" varchar(500) NULL,
    "CompanyName" varchar(500) NULL,
    "ResidenceTypeId" varchar(50) NULL,
    "ResidenceTypeIdText" varchar(500) NULL,
    "Description" varchar(500) NULL,
    "CompanyNameInv" varchar(500) NULL,
    "EmailInv" varchar(255) NULL,
    "AssignmentDebitId" varchar(50) NULL,
    "AssignmentInvId" varchar(50) NULL,
    "AccountNumber" varchar(50) NULL,
    "AccountName" varchar(255) NULL,
    "BankId" varchar(50) NULL,
    "AccountBranch" varchar(250) NULL,
    "SwiftCode" varchar(50) NULL,
    "OpenedAt" varchar(250) NULL,
    "IdCode" varchar(50) NULL,
    "Password" varchar(255) NULL,
    "Industry" varchar(255) NULL,
    "Po" varchar(255) NULL,
    "RushMonth" int NULL,
    "Rating" varchar(255) NULL,
    "PoDate" timestamptz NULL,
    "MinProfitMonth" numeric(19,4) NULL,
    "ToastWarning" varchar(255) NULL,
    "ActionId" int NULL,
    "RegularShippingFrom" varchar(255) NULL,
    "ConditionId" varchar(50) NULL,
    "DistributeInformationIds" varchar(255) NULL,
    "DistributeInformationIdsText" varchar(255) NULL,
    "ZipCode" varchar(50) NULL,
    "TrackingURL" varchar(50) NULL,
    "IsNoDebt" boolean NOT NULL,
    "PartnerTypeIds" varchar(255) NULL,
    "PartnerTypeIdsText" varchar(255) NULL,
    "FormatChat" varchar(250) NULL,
    "AddressInv" varchar(250) NULL,
    "AssignId" varchar(50) NULL,
    "History" varchar(500) NULL,
    "Birthday" timestamptz NULL,
    "Logo" varchar(500) NULL,
    "WebSite" varchar(500) NULL,
    "Fax" varchar(50) NULL,
    "ReceivesAccountNumber" varchar(50) NULL,
    "ReceivesAccountName" varchar(255) NULL,
    "ReceivesBankId" varchar(50) NULL,
    "ReceivesSwiftCode" varchar(50) NULL,
    "CustomerTypeIdText" varchar(255) NULL,
    "FeatureName" varchar(500) NULL,
    "Header" varchar(4000) NULL,
    "Footer" varchar(4000) NULL,
    PRIMARY KEY ("Id")
);

-- Role table
CREATE TABLE "Role" (
    "Id" varchar(50) NOT NULL,
    "Hidden" boolean NOT NULL DEFAULT false,
    "Name" varchar(250) NULL,
    "Description" varchar(250) NULL,
    "Active" boolean NOT NULL DEFAULT false,
    "InsertedBy" varchar(50) NULL,
    "InsertedDate" timestamptz NULL,
    "UpdatedBy" varchar(50) NULL,
    "UpdatedDate" timestamptz NULL,
    "created_by" varchar(255) NULL,
    PRIMARY KEY ("Id")
);

-- Tanent table
CREATE TABLE "Tanent" (
    "Id" varchar(50) NOT NULL,
    "Password" varchar(250) NULL,
    "CompanyName" varchar(250) NULL,
    "TaxCode" varchar(250) NULL,
    "TanentCode" varchar(250) NULL,
    "Active" boolean NOT NULL,
    "InsertedBy" varchar(50) NULL,
    "InsertedDate" timestamptz NULL,
    "UpdatedBy" varchar(50) NULL,
    "UpdatedDate" timestamptz NULL,
    PRIMARY KEY ("Id")
);

-- TaskNotification table
CREATE TABLE "TaskNotification" (
    "Id" varchar(50) NOT NULL,
    "Read" boolean NOT NULL DEFAULT false,
    "Icon" varchar(150) NULL,
    "AssignedId" varchar(50) NULL,
    "EntityId" varchar(250) NULL,
    "Avatar" varchar(2500) NULL,
    "FromName" varchar(2500) NULL,
    "FeatureName" varchar(500) NULL,
    "FeatureName2" varchar(500) NULL,
    "FeatureName3" varchar(500) NULL,
    "Title" varchar(2500) NULL,
    "Title2" varchar(2500) NULL,
    "Description" varchar(2500) NULL,
    "Description2" varchar(2500) NULL,
    "Active" boolean NOT NULL DEFAULT false,
    "InsertedDate" timestamptz NULL,
    "InsertedBy" varchar(50) NULL,
    "UpdatedDate" timestamptz NULL,
    "UpdatedBy" varchar(50) NULL,
    "RecordId" varchar(50) NULL,
    "VoucherTypeId" int NULL,
    PRIMARY KEY ("Id")
);

-- User table
CREATE TABLE "User" (
    "Id" varchar(50) NOT NULL,
    "Code" varchar(250) NULL,
    "Email" varchar(250) NULL,
    "Password" varchar(250) NULL,
    "Salt" varchar(250) NULL,
    "UserName" varchar(250) NULL,
    "FullName" varchar(250) NULL,
    "Address" varchar(250) NULL,
    "Avatar" varchar(250) NULL,
    "Ssn" varchar(250) NULL,
    "PhoneNumber" varchar(250) NULL,
    "TeamId" varchar(50) NULL,
    "PartnerId" varchar(50) NULL,
    "Active" boolean NOT NULL DEFAULT false,
    "InsertedBy" varchar(50) NULL,
    "InsertedDate" timestamptz NULL,
    "UpdatedBy" varchar(50) NULL,
    "UpdatedDate" timestamptz NULL,
    "Dob" timestamptz NULL,
    "GenderId" varchar(50) NULL,
    "SsnDate" timestamptz NULL,
    "TaxCode" varchar(50) NULL,
    "SeqKey" int NULL,
    "LoginFailedCount" int NULL,
    "LastFailedLogin" timestamptz NULL,
    "LastLogin" timestamptz NULL,
    "Recover" varchar(500) NULL,
    "JointDate" timestamptz NULL,
    "RoleIds" varchar(500) NULL,
    "RoleIdsText" varchar(500) NULL,
    "DepartmentId" varchar(50) NULL,
    "IdentityCardDate" timestamptz NULL,
    "IdentityCard" varchar(150) NULL,
    "PlaceIssue" varchar(150) NULL,
    "NickName" varchar(150) NULL,
    "Knowledge" varchar(150) NULL,
    "TargetLocalCurr" numeric(19,4) NULL,
    "TargetUSDCurr" numeric(19,4) NULL,
    "TypeBonusId" varchar(50) NULL,
    "SalaryAmount" numeric(19,4) NULL,
    "SalaryCoefficient" numeric(19,4) NULL,
    "InsuranceAmount" numeric(19,4) NULL,
    "TypeContractId" varchar(50) NULL,
    "Dependents" int NULL,
    "AccNumber" varchar(50) NULL,
    "AccName" varchar(255) NULL,
    "BankId" varchar(50) NULL,
    "PassEmail" varchar(255) NULL,
    "CompanyId" varchar(50) NULL,
    "IsDepartment" boolean NOT NULL DEFAULT false,
    "IsTeam" boolean NOT NULL DEFAULT false,
    "PositionId" varchar(50) NULL,
    "TypeId" int NULL,
    "MailServer" varchar(250) NULL,
    "PortServer" varchar(250) NULL,
    PRIMARY KEY ("Id")
);

-- UserLogin table
CREATE TABLE "UserLogin" (
    "Id" varchar(50) NOT NULL,
    "UserId" varchar(50) NULL,
    "AccessToken" varchar(1500) NULL,
    "RefreshToken" varchar(1500) NULL,
    "AccessTokenExp" timestamptz NULL,
    "RefreshTokenExp" timestamptz NULL,
    "Active" boolean NOT NULL DEFAULT false,
    "InsertedBy" varchar(50) NULL,
    "InsertedDate" timestamptz NULL,
    "UpdatedBy" varchar(50) NULL,
    "UpdatedDate" timestamptz NULL,
    "created_by" varchar(255) NULL,
    "IpAddress" varchar(255) NULL,
    PRIMARY KEY ("Id")
);

-- UserRole table
CREATE TABLE "UserRole" (
    "Id" varchar(50) NOT NULL,
    "UserId" varchar(50) NULL,
    "RoleId" varchar(50) NULL,
    "Active" boolean NOT NULL DEFAULT false,
    "InsertedBy" varchar(50) NULL,
    "InsertedDate" timestamptz NULL,
    "UpdatedBy" varchar(50) NULL,
    "UpdatedDate" timestamptz NULL,
    "created_by" varchar(255) NULL,
    PRIMARY KEY ("Id")
);

-- UserSetting table
CREATE TABLE "UserSetting" (
    "Id" varchar(50) NOT NULL,
    "FeatureId" varchar(50) NULL,
    "ComponentId" varchar(50) NULL,
    "UserId" varchar(50) NULL,
    "Value" text NULL,
    "Active" boolean NOT NULL DEFAULT false,
    "InsertedDate" timestamptz NULL,
    "InsertedBy" varchar(50) NULL,
    "UpdatedDate" timestamptz NULL,
    "UpdatedBy" varchar(50) NULL,
    PRIMARY KEY ("Id")
);
