<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="wwwroot\excel\**" />
	  <Compile Remove="wwwroot\upload\**" />
	  <Content Remove="wwwroot\excel\**" />
	  <Content Remove="wwwroot\upload\**" />
	  <EmbeddedResource Remove="wwwroot\excel\**" />
	  <EmbeddedResource Remove="wwwroot\upload\**" />
	  <None Remove="wwwroot\excel\**" />
	  <None Remove="wwwroot\upload\**" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="wwwroot\upload\crm\features\account-transfer-setup.json" />
	  <Content Include="wwwroot\upload\crm\features\accounting.json" />
	  <Content Include="wwwroot\upload\crm\features\accountno-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\accountno.json" />
	  <Content Include="wwwroot\upload\crm\features\advance-request-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\advance-request.json" />
	  <Content Include="wwwroot\upload\crm\features\air-booking-local-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\air-booking-local.json" />
	  <Content Include="wwwroot\upload\crm\features\air-booking-note-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\air-booking-note.json" />
	  <Content Include="wwwroot\upload\crm\features\air-booking-order-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\air-booking-order.json" />
	  <Content Include="wwwroot\upload\crm\features\air-export-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\air-export.json" />
	  <Content Include="wwwroot\upload\crm\features\air-import-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\air-import.json" />
	  <Content Include="wwwroot\upload\crm\features\air-pricing-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\air-pricing.json" />
	  <Content Include="wwwroot\upload\crm\features\air-quote-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\air-quote.json" />
	  <Content Include="wwwroot\upload\crm\features\all-partner.json" />
	  <Content Include="wwwroot\upload\crm\features\allocation-cost-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\approval-config.json" />
	  <Content Include="wwwroot\upload\crm\features\approval-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\bank.json" />
	  <Content Include="wwwroot\upload\crm\features\booking-local.json" />
	  <Content Include="wwwroot\upload\crm\features\booking-note.json" />
	  <Content Include="wwwroot\upload\crm\features\booking-order.json" />
	  <Content Include="wwwroot\upload\crm\features\budget.json" />
	  <Content Include="wwwroot\upload\crm\features\category.json" />
	  <Content Include="wwwroot\upload\crm\features\change-password-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\chart-of-Accounts .json" />
	  <Content Include="wwwroot\upload\crm\features\chat-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\chat.json" />
	  <Content Include="wwwroot\upload\crm\features\commodity.json" />
	  <Content Include="wwwroot\upload\crm\features\company-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\company.json" />
	  <Content Include="wwwroot\upload\crm\features\component-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\component-editor2.json" />
	  <Content Include="wwwroot\upload\crm\features\config-code.json" />
	  <Content Include="wwwroot\upload\crm\features\config-unique.json" />
	  <Content Include="wwwroot\upload\crm\features\container-type.json" />
	  <Content Include="wwwroot\upload\crm\features\cost-of-production.json" />
	  <Content Include="wwwroot\upload\crm\features\country.json" />
	  <Content Include="wwwroot\upload\crm\features\currency.json" />
	  <Content Include="wwwroot\upload\crm\features\customer-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\customer.json" />
	  <Content Include="wwwroot\upload\crm\features\daily-email.json" />
	  <Content Include="wwwroot\upload\crm\features\debt-accounting-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\debt-report.json" />
	  <Content Include="wwwroot\upload\crm\features\email-template-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\equipments.json" />
	  <Content Include="wwwroot\upload\crm\features\exchange-rate.json" />
	  <Content Include="wwwroot\upload\crm\features\feature-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\fee.json" />
	  <Content Include="wwwroot\upload\crm\features\financial-analysis.json" />
	  <Content Include="wwwroot\upload\crm\features\fixed-assets.json" />
	  <Content Include="wwwroot\upload\crm\features\flow-manage.json" />
	  <Content Include="wwwroot\upload\crm\features\flows-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\flows.json" />
	  <Content Include="wwwroot\upload\crm\features\general.json" />
	  <Content Include="wwwroot\upload\crm\features\group-fee.json" />
	  <Content Include="wwwroot\upload\crm\features\history.json" />
	  <Content Include="wwwroot\upload\crm\features\inquiry-detail-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\inquiry-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\inquiry.json" />
	  <Content Include="wwwroot\upload\crm\features\Inventory.json" />
	  <Content Include="wwwroot\upload\crm\features\Invoice Managing.json" />
	  <Content Include="wwwroot\upload\crm\features\invoice-config.json" />
	  <Content Include="wwwroot\upload\crm\features\invoice-management.json" />
	  <Content Include="wwwroot\upload\crm\features\issue-invoice-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\lang.json" />
	  <Content Include="wwwroot\upload\crm\features\leads-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\leads.json" />
	  <Content Include="wwwroot\upload\crm\features\loan-connection.json" />
	  <Content Include="wwwroot\upload\crm\features\login.json" />
	  <Content Include="wwwroot\upload\crm\features\logistics-booking-local-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\logistics-booking-local.json" />
	  <Content Include="wwwroot\upload\crm\features\logistics-pricing-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\logistics-pricing.json" />
	  <Content Include="wwwroot\upload\crm\features\logistics-quote-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\logistics-quote.json" />
	  <Content Include="wwwroot\upload\crm\features\mail-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\markup-pricing.json" />
	  <Content Include="wwwroot\upload\crm\features\master-data.json" />
	  <Content Include="wwwroot\upload\crm\features\menu.json" />
	  <Content Include="wwwroot\upload\crm\features\my-shipment.json" />
	  <Content Include="wwwroot\upload\crm\features\other-booking-order-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\other-booking-order.json" />
	  <Content Include="wwwroot\upload\crm\features\overview-docs.json" />
	  <Content Include="wwwroot\upload\crm\features\overview-sales.json" />
	  <Content Include="wwwroot\upload\crm\features\partner-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\partner.json" />
	  <Content Include="wwwroot\upload\crm\features\partners.json" />
	  <Content Include="wwwroot\upload\crm\features\payment-accounting-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\payment-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\payment-manage.json" />
	  <Content Include="wwwroot\upload\crm\features\payment-request-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\payment-request.json" />
	  <Content Include="wwwroot\upload\crm\features\payroll.json" />
	  <Content Include="wwwroot\upload\crm\features\personal-contact-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\personal-contact.json" />
	  <Content Include="wwwroot\upload\crm\features\pricing.json" />
	  <Content Include="wwwroot\upload\crm\features\production-report.json" />
	  <Content Include="wwwroot\upload\crm\features\profile.json" />
	  <Content Include="wwwroot\upload\crm\features\profit-report.json" />
	  <Content Include="wwwroot\upload\crm\features\proof-of-delivery-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\prospect-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\prospect.json" />
	  <Content Include="wwwroot\upload\crm\features\provider-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\provider.json" />
	  <Content Include="wwwroot\upload\crm\features\purchase.json" />
	  <Content Include="wwwroot\upload\crm\features\quote.json" />
	  <Content Include="wwwroot\upload\crm\features\receipt-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\reimbursement-form-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\report.json" />
	  <Content Include="wwwroot\upload\crm\features\role-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\role.json" />
	  <Content Include="wwwroot\upload\crm\features\sales-function.json" />
	  <Content Include="wwwroot\upload\crm\features\sales.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-booking-local-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-booking-local.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-booking-note-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-booking-note.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-booking-order-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-booking-order.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-export-consol-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-export-consol.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-export-fcl-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-export-fcl.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-export-lcl-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-export-lcl.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-import-consol-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-import-consol.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-import-fcl-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-import-fcl.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-import-lcl-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-import-lcl.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-pricing-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-pricing.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-quote-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\sea-quote.json" />
	  <Content Include="wwwroot\upload\crm\features\section-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\section-editor2.json" />
	  <Content Include="wwwroot\upload\crm\features\send-mail.json" />
	  <Content Include="wwwroot\upload\crm\features\service.json" />
	  <Content Include="wwwroot\upload\crm\features\shipment-process-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\shipment-process.json" />
	  <Content Include="wwwroot\upload\crm\features\shipment.json" />
	  <Content Include="wwwroot\upload\crm\features\shipper.json" />
	  <Content Include="wwwroot\upload\crm\features\shipping-instruction-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\soa-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\submit-si-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\submit-si.json" />
	  <Content Include="wwwroot\upload\crm\features\system.json" />
	  <Content Include="wwwroot\upload\crm\features\table-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\table-manage.json" />
	  <Content Include="wwwroot\upload\crm\features\table.json" />
	  <Content Include="wwwroot\upload\crm\features\tax.json" />
	  <Content Include="wwwroot\upload\crm\features\team-group.json" />
	  <Content Include="wwwroot\upload\crm\features\terminal-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\terminal.json" />
	  <Content Include="wwwroot\upload\crm\features\track-trace-air.json" />
	  <Content Include="wwwroot\upload\crm\features\track-trace-sea.json" />
	  <Content Include="wwwroot\upload\crm\features\trucking-booking-local-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\trucking-booking-local.json" />
	  <Content Include="wwwroot\upload\crm\features\trucking-pricing-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\trucking-pricing.json" />
	  <Content Include="wwwroot\upload\crm\features\trucking-quote-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\trucking-quote.json" />
	  <Content Include="wwwroot\upload\crm\features\trucking-shipment-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\trucking-shipment.json" />
	  <Content Include="wwwroot\upload\crm\features\unit.json" />
	  <Content Include="wwwroot\upload\crm\features\update-exchangerate-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\user-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\user-profile.json" />
	  <Content Include="wwwroot\upload\crm\features\users.json" />
	  <Content Include="wwwroot\upload\crm\features\vat-invoice.json" />
	  <Content Include="wwwroot\upload\crm\features\vatinvoice-editor.json" />
	  <Content Include="wwwroot\upload\crm\features\voucher-management.json" />
	  <Content Include="wwwroot\upload\crm\features\web-config.json" />
	  <Content Include="wwwroot\upload\crm\features\workflow-manage.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.104.2" />
		<PackageReference Include="DuckDB.NET.Data.Full" Version="1.2.1" />
		<PackageReference Include="Hangfire" Version="1.8.18" />
		<PackageReference Include="HtmlAgilityPack.NetCore" Version="1.5.0.1" />
		<PackageReference Include="LinqKit" Version="1.3.8" />
		<PackageReference Include="MailKit" Version="4.11.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.3" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.3">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.SqlServer.DacFx" Version="162.5.57" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3" />
    <PackageReference Include="OpenAI" Version="2.1.0" />
		<PackageReference Include="PuppeteerSharp" Version="20.1.3" />
		<PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
		<PackageReference Include="Topaz" Version="1.4.1" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Migrations\" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="wwwroot\upload\crm\db\202511221_schema.sql" />
	  <None Include="wwwroot\upload\crm\db\202511222_seed.sql" />
	  <None Include="wwwroot\upload\crm\db\init.sh" />
	</ItemGroup>

</Project>
