# For more info on HTTP files go to https://aka.ms/vs/httpfile
POST https://localhost:5033/api/cluster/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL2dyb3Vwc2lkIjoiNjM3MTEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic3lzIiwiQnJhbmNoSWQiOiI3NjMyIiwiZW1haWwiOiIiLCJiaXJ0aGRhdGUiOiIiLCJmYW1pbHlfbmFtZSI6Ikjhu4cgdGjhu5FuZyIsImlhdCI6IjEyLzI1LzIwMjMgMTE6NDY6MTMgQU0gKzA3OjAwIiwianRpIjoiMjY4MTQyMDItYTQ3ZS00OGFiLWIxM2ItNjA5MTExM2YxNDg4IiwiVGVuYW50Q29kZSI6IlN5c3RlbSIsIkVudmlyb25tZW50IjoidGVzdCIsIkNvbm5LZXkiOiJkZWZhdWx0IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwOS8wOS9pZGVudGl0eS9jbGFpbXMvYWN0b3IiOiI4IiwiUm9sZSI6IlN5c3RlbSIsImV4cCI6MTcwMzU2NTk3MywiaXNzIjoiaHR0cHM6Ly90bXMuc29mdGVrLmNvbS52bi8iLCJhdWQiOiJodHRwczovL3Rtcy5zb2Z0ZWsuY29tLnZuLyJ9.wQFO4ghr8eBbkfxJ44JYCCr-hTWYJVRnF0N1Wt3Xytc
{
  "Host": "localhost",
  "Port": 5002
}