# For more info on HTTP files go to https://aka.ms/vs/httpfile
POST https://localhost:5033/api/cluster/add
Content-Type: application/json
Connection: hub
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL2dyb3Vwc2lkIjoiNjM3MTEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic3lzIiwiQnJhbmNoSWQiOiI3NjMyIiwiZW1haWwiOiIiLCJiaXJ0aGRhdGUiOiIiLCJmYW1pbHlfbmFtZSI6Ikjhu4cgdGjhu5FuZyIsImlhdCI6IjEyLzI2LzIwMjMgMjoyMjoxMyBQTSArMDc6MDAiLCJqdGkiOiIwZGQyNmU3Mi0zZjViLTQzYzEtOTk3YS1hOGU0ZGE5MzA5YWMiLCJUZW5hbnRDb2RlIjoiU3lzdGVtIiwiRW52aXJvbm1lbnQiOiJ0ZXN0IiwiQ29ubktleSI6ImRlZmF1bHQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA5LzA5L2lkZW50aXR5L2NsYWltcy9hY3RvciI6IjgiLCJSb2xlIjoiU3lzdGVtIiwiZXhwIjoxNzAzNjYxNzMzLCJpc3MiOiJodHRwczovL3Rtcy5zb2Z0ZWsuY29tLnZuLyIsImF1ZCI6Imh0dHBzOi8vdG1zLnNvZnRlay5jb20udm4vIn0.H7pI7z-IEmmVFJr2H09p4NoLJO8BGwxn34vMdMoN75g
{
  "Id": "e3af57b0-8c44-415e-af78-7e5c4b8bfe83",
  "Host": "localhost",
  "Port": 5002,
  "Scheme": "http",
  "Role": "API"
}