name: CI/CD Pipeline

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata for Docker
        id: meta
        run: |
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # CoreAPI Build with Cache
      - name: Build and Push CoreAPI Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./CoreAPI
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/corejs-coreapi:latest
            ${{ secrets.DOCKER_USERNAME }}/corejs-coreapi:${{ steps.meta.outputs.date }}-${{ steps.meta.outputs.sha_short }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/corejs-coreapi:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/corejs-coreapi:buildcache,mode=max

      # Frontend Build with Cache and Dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm ci

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/corejs-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/corejs-frontend:${{ steps.meta.outputs.date }}-${{ steps.meta.outputs.sha_short }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/corejs-frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/corejs-frontend:buildcache,mode=max
          build-args: |
            NODE_ENV=production

      - name: Deploy Application
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          USERNAME: ${{ secrets.USERNAME }}
          SERVER: ${{ secrets.SERVER }}
          PORT: ${{ secrets.PORT }}
          DESTINATION_PATH: "/home/${{ secrets.USERNAME }}/deployments/corejs"
          IMAGE_TAG: "${{ steps.meta.outputs.date }}-${{ steps.meta.outputs.sha_short }}"
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
        run: |
          # Install sshpass for password-based authentication
          sudo apt-get update && sudo apt-get install -y sshpass
      
          # First create the directory, then copy the deployment script to the target server
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $PORT $USERNAME@$SERVER "mkdir -p $DESTINATION_PATH"
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -P $PORT scripts/deploy.sh $USERNAME@$SERVER:$DESTINATION_PATH/
      
          # Create a temporary file with the new environment variables
          cat > temp_env << EOF
          DOCKER_USERNAME=${DOCKER_USERNAME}
          DOCKER_PASSWORD=${DOCKER_PASSWORD}
          IMAGE_TAG=${IMAGE_TAG}
          ALLOWED_HOSTS=${ALLOWED_HOSTS}
          # Keep other existing variables that shouldn't change
          EOF

          # Securely transfer and replace the .env file
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -P $PORT temp_env $USERNAME@$SERVER:$DESTINATION_PATH/temp.env
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $PORT $USERNAME@$SERVER "
            # If there's an existing .env file, preserve variables not in temp.env
            if [ -f $DESTINATION_PATH/.env ]; then
              grep -v '^DOCKER_USERNAME=\|^DOCKER_PASSWORD=\|^IMAGE_TAG=\|^ALLOWED_HOSTS=' $DESTINATION_PATH/.env > $DESTINATION_PATH/preserved_env || true
              cat $DESTINATION_PATH/preserved_env $DESTINATION_PATH/temp.env > $DESTINATION_PATH/.env
              rm $DESTINATION_PATH/preserved_env $DESTINATION_PATH/temp.env
            else
              mv $DESTINATION_PATH/temp.env $DESTINATION_PATH/.env
            fi
            chmod 600 $DESTINATION_PATH/.env  # Restrict permissions to owner only
          "

          # Remove the local temporary file
          rm temp_env
          
          # Run the deployment script in the correct directory and clean up
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $PORT $USERNAME@$SERVER "
            cd $DESTINATION_PATH &&
            chmod +x deploy.sh &&
            bash deploy.sh &&
            rm -f deploy.sh
          "