name: CI/CD Pipeline

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm ci
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Enable BuildKit
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/corejs-coreapi:latest
            ${{ secrets.DOCKER_USERNAME }}/corejs-frontend:latest
          file: compose.yml
          builder: default

      - name: Generate and Run Deployment Script
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          USERNAME: ${{ secrets.USERNAME }}
          SERVER: ${{ secrets.SERVER }}
          PORT: ${{ secrets.PORT }}
          DESTINATION_PATH: "/home/${{ secrets.USERNAME }}/deployments/corejs"
        run: |
          cat <<EOF > deploy.sh
          #!/bin/bash
          set -e

          echo "Checking if Docker Compose is installed..."
          if ! command -v docker-compose &> /dev/null; then
            echo "Docker Compose not found. Installing..."
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-\$(uname -s)-\$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
          else
            echo "Docker Compose is already installed."
          fi

          echo "Logging into Docker Hub..."
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

          echo "Pulling Docker images..."
          docker pull $DOCKER_USERNAME/corejs-coreapi:latest
          docker pull $DOCKER_USERNAME/corejs-frontend:latest

          echo "Generating docker-compose.yml..."
          cat <<COMPOSE > docker-compose.yml
          version: '3.8'

          services:
            coreapi:
              image: $DOCKER_USERNAME/corejs-coreapi:latest
              ports:
                - "8000:8000"

            frontend:
              image: $DOCKER_USERNAME/corejs-frontend:latest
              ports:
                - "3000:3000"
          COMPOSE

          echo "Starting the application..."
          docker compose up -d
          EOF

          chmod +x deploy.sh

          # Install sshpass for password-based authentication
          sudo apt-get update && sudo apt-get install -y sshpass

          # Copy the deployment script to the target server
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -P $PORT deploy.sh $USERNAME@$SERVER:$DESTINATION_PATH/

          # Run the deployment script on the target server and clean up
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $PORT $USERNAME@$SERVER "
            chmod +x $DESTINATION_PATH/deploy.sh &&
            bash $DESTINATION_PATH/deploy.sh &&
            rm -f $DESTINATION_PATH/deploy.sh
          "